### ISSUE TITLE
Trying to download the plug in but it keeps saying plug in site unavailable 

### ISSUE THREAD

**Issue by TCLGuy1** [hjdhjd/homebridge-myq#1001]
**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by TCLGuy1** [comment]
![Screen Shot 2023-02-21 at 11 38 28 AM](https://user-images.githubusercontent.com/104545628/220442160-6eb2351d-098c-482f-8108-a8c27b14df50.png)

**Comment by Bgoshua** [comment]
> ![Screen Shot 2023-02-21 at 11 38 28 AM](https://user-images.githubusercontent.com/104545628/220442160-6eb2351d-098c-482f-8108-a8c27b14df50.png)
> 
> 

I believe this is a known issue with Hoobs and not this plugin. Try this:

https://support.hoobs.org/topics/connectivity/plugin-site-unavailable
