### ISSUE TITLE
Shortcuts State Shows as Numbers

### ISSUE THREAD

**Issue by CipherTheWolf** [hjdhjd/homebridge-myq#1022]
**Describe The Problem:**
<When attempting to build a button to open and close MyQ garage door in Shortcuts, setting the current state looks for a numerical entry, not text options like Open, Closed, Obstructed. When I previously did this with this plugin a little over a year ago, those options were there. Not sure if the issue is on this plugin or user error (very likely).>

**To Reproduce:**
<Open Shortcuts, create new Shortcut, add IF, select Home as input, select MyQ, select current door state, set condition to IS, Choose shows 0,1,2,3,4 (not Open, Closed, Obstructed)>

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
    {
            "email": "xxx@email.com",
            "password": "X123",
            "name": "myQ",
            "platform": "myQ",
            "_bridge": {
                "username": "......",
                "port": 32626
            }
```

**Screenshots:**

<img width="1197" alt="Screenshot 2023-03-12 at 9 39 21 PM" src="https://user-images.githubusercontent.com/22479149/224595907-b52a863c-5b2b-499a-bf4c-3f6b3ee3f13c.png">

**Environment:**

* **Homebridge Version:** <v1.6.0 (HAP v0.11.0) (Homebridge 593D)>
* **Node Version:** <[v18.13.0]>
* **Homebridge-myQ Plugin Versionv2.9.0:
* **macOS  Version: 13.2.1
* **Operating System and OS Version:** <Raspbian GNU/Linux Bullseye (11)>

**Comment by CipherTheWolf** [comment]
Thanks in advance for your help and support for the community!

**Comment by hjdhjd** [comment]
Thanks for the report, but unfortunately there’s nothing I can do on the plugin end. This appears to be an issue in the Shortcuts UI not HBMQ. I’d suggest filing a bug report with Apple. Best of luck!
