### ISSUE TITLE
Unable to control myq for open / close

### ISSUE THREAD

**Issue by levibrown** [hjdhjd/homebridge-myq#1038]
As a first time user of homebridge and this plugin, I went through the documented configuration and everything seemed to work well.  I can see my garage door in my Home app, but I am un able to control the door.  When I slide to door switch up(or down), on screen it says that its opening, but the door doesn't respond.

Setup was done through the homebridge UI/
User name and password was verified and double checked in the json.

note: i do get iOS notifications for when the door is open or closed (via myQ app), but they are delayed.

**Logs:**
I get multiple of these messages in the logs, which seems like it might be related to the problem.
```
[26/03/2023, 18:19:49] [myQ] myQ API: Successfully connected to the myQ API.

[26/03/2023, 18:20:22] [myQ] myQ API: Hostname or IP address not found.
[26/03/2023, 18:20:22] [myQ] myQ API: Unable to retrieve account information.
```

**Homebridge Configuration:**
```json
{
    "bridge": {
        "name": "Homebridge 7E25",
        "username": "xxxxx",
        "port": 51707,
        "pin": "xxxxx",
        "advertiser": "resolved"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-blue-grey",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "xxxxxxx",
            "password": "xxxxxx",
            "name": "myQ",
            "debug": true,
            "_bridge": {
                "username": "xxxxxxxxxx",
                "port": 30405
            },
            "platform": "myQ"
        }
    ]
}
```

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** v18.12.1
* **Homebridge-myQ Plugin Version**: v2.9.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS v16.3.1
* **Operating System and OS Version:** Raspbian GNU/Linux Bullseye (11)

**Comment by hjdhjd** [comment]
Welcome to the community. Looks like potentially a DNS or connectivity issue. Try restarting Homebridge and see if that does the trick.

**Comment by levibrown** [comment]
thank you, good to be here.   
turns out it was something simple like that.  I had already restarted homebridge several times, but I was able to get it working after a power down/ up of the raspberrypi.  Thanks for your response and maintenance of this plugin!
