### ISSUE TITLE
Enhancement - myQ Camera integrated opener

### ISSUE THREAD

**Issue by Zsoldier** [hjdhjd/homebridge-myq#105]
Want to see about getting this support added.  I can probably help out nights and weekends.

**Comment by Tribruin** [comment]
Adding my support to help work on this.

**Comment by hjdhjd** [comment]
Awesome. Let’s see what we can make work. We need to get some data from your respective setups. Stay tuned.

**Comment by hjdhjd** [comment]
Hi guys - can you elaborate on your individual myQ hardware setups, and how you access camera / video now? Let's see if we can get this working in HomeKit. :smile:

**Comment by Zsoldier** [comment]
Bought a Chamberlain B6765 Garage Door Opener recently.  Has a built-in webcam.  I also bought the native myQ homebridge MYQ-G0303-SP to see if it would pass the camera to homekit, but it only is capable of integrating with opener or light devices.  Not the camera itself.

**Comment by Zsoldier** [comment]
![image](https://user-images.githubusercontent.com/7501186/92517282-67879e00-f1e4-11ea-9cf4-173cc45af49f.png)

**Comment by Zsoldier** [comment]
![image](https://user-images.githubusercontent.com/7501186/92517338-7f5f2200-f1e4-11ea-9158-03a6a3872f91.png)

**Comment by hjdhjd** [comment]
So here’s the question here...can you upgrade to the latest version of the plugin, and post the log output when you first start Homebridge? I’m just looking for the lines that start with myQ. Specifically, I’m trying to see what devices the plugin detects and if it even sees the camera devices. Let’s see what we’re working with.

Thanks!

**Comment by Zsoldier** [comment]
[9/16/2020, 11:06:39 PM] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CGxxxxxxxAxxx, gateway: GW2xxxxxxxxxx).
[9/16/2020, 11:06:39 PM] [myQ] myQ API: Discovered device family hawkeyecamera: Garage Door Camera (serial number: TC-xxxx-598xxxx).
[9/16/2020, 11:06:39 PM] [myQ] myQ API: Discovered device family gateway: HomeBridge [Chamberlain myQ Home Bridge] (serial number: GW2xxxxxxxxx).
[9/16/2020, 11:06:39 PM] [myQ] Garage Door: Adding garagedoor device to HomeKit: Garage Door (serial number: CG0xxxxxxAxx, gateway: GW2xxxxxxxxxx).
[9/16/2020, 11:06:39 PM] [myQ] myQ device family 'hawkeyecamera' is not currently supported, ignoring: Garage Door Camera (serial number: TC-xxxx-598xxxxx).

**Comment by hjdhjd** [comment]
Tantalizing.

Alright...good news is that the camera’s exposed through the myQ API it seems. Now, next step...enable debugging in the plugin (look for it under advanced settings in the Homebridge webUI). When you do, you’re going to get a lot of data in your logs. Specifically, you’re going to see a series of JSONs repeatedly show up...I need that series of JSONs and I can begin figuring out how to make all this work. Feel free to mask any sensitive information before posting it.

I wouldn’t leave debug logging on for too long...it is very spammy. 😄

**Comment by Zsoldier** [comment]
Hmm, I'm getting plenty of additional info from my other plugins, but a whole lot of nothing from myQ plugin.  I put homebridge in debug mode.  I also tried setting env var debug to 'true' and to '1', but didn't get much of a difference in return.

Ring plugin definitely returns me a crap ton of info, but no myQ.

**Comment by Zsoldier** [comment]
Nvm, I see the flag under plugin.

**Comment by hjdhjd** [comment]
You’re overthinking it. 😄

**Comment by hjdhjd** [comment]
There you go...

**Comment by Zsoldier** [comment]
Success!
`[9/18/2020, 8:50:09 PM] [myQ] {
  Account: {
    AccessGroups: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xxAccessGroups'
    },
    AccessSchedules: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xx/AccessSchedules'
    },
    Address: {
      AddressLine1: '',
      AddressLine2: '',
      City: '',
      Country: {
        Code: 'USA',
        IsEEACountry: false,
        href: 'http://api.myqdevice.com/api/v5/Countries/USA'
      },
      PostalCode: 'xxxxx',
      State: ''
    },
    ContactName: 'xx',
    Devices: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xx/Devices'
    },
    DirectoryCodeLength: 0,
    Email: ',
    Id: 'xx',
    Name: "xx",
    Roles: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/x/Roles'
    },
    TimeZone: 'America/New_York',
    UserAllowance: 4,
    Users: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xx/Users'
    },
    Zones: {
      href: 'http://api.myqdevice.com/api/v5/Accounts/xx/Zones'
    },
    href: 'http://api.myqdevice.com/api/v5/Accounts/'
  },
  Address: {
    AddressLine1: '',
    AddressLine2: '',
    City: '',
    Country: {
      Code: 'USA',
      IsEEACountry: false,
      href: 'http://api.myqdevice.com/api/v5/Countries/USA'
    },
    PostalCode: '',
    State: ''
  },
  Admin: false,
  AnalyticsId: '',
  CultureCode: 'en',
  DiagnosticDataOptIn: true,
  Email: ',
  FirstName: 'xx',
  LastName: 'xx',
  MailingListOptIn: false,
  Phone: '',
  RequestAccountLinkInfo: false,
  TimeZone: { Id: 'America/New_York', Name: 'America/New_York' },
  UserId: '',
  UserName: ',
  Users: { href: '' }
  }
[9/18/2020, 8:50:12 PM] [myQ] {
  count: 3,
  href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices',
  items: [
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'garagedoor',
      device_platform: 'myq',
      device_type: 'wifigaragedooropener',
      href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/CGxxxxxxxxxx',
      name: 'Garage Door',
      parent_device: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/GWxxxxxxxxxx',
      parent_device_id: 'GWxxxxxxxxxx',
      serial_number: 'CGxxxxxxxxxx',
      state: {
        attached_work_light_error_present: false,
        aux_relay_behavior: 'None',
        aux_relay_delay: '00:00:00',
        close: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/CGxxxxxxxxxx/close',
        command_channel_report_status: false,
        control_from_browser: false,
        door_ajar_interval: '00:00:00',
        door_state: 'closed',
        gdo_lock_connected: false,
        invalid_credential_window: '00:00:00',
        invalid_shutout_period: '00:00:00',
        is_unattended_close_allowed: true,
        is_unattended_open_allowed: true,
        last_status: '2020-09-19T00:49:14.2664737Z',
        last_update: '2020-09-18T23:38:05.6490848Z',
        max_invalid_attempts: 0,
        online: true,
        open: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/CGxxxxxxxxxx/open',
        passthrough_interval: '00:00:00',
        report_ajar: false,
        report_forced: false,
        rex_fires_door: false,
        use_aux_relay: false
      }
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'hawkeyecamera',
      device_platform: 'myq',
      device_type: 'hawkeyecamera',
      href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/TC-xxxx-xxxxxxx',
      name: 'Garage Door Camera',
      serial_number: 'TC-xxxx-xxxxxxx',
      state: {
        last_event: 'MotionDetected',
        last_status: '2020-09-19T00:09:33Z',
        last_update: '2020-09-19T00:09:33Z',
        links: {
          events: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/TC-xxxx-xxxxxxx/events',
          stream: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/TC-xxxx-xxxxxxx/stream'
        },
        online: true,
        online_change_time: '2020-09-09T23:38:38Z',
        servers: 'https://v2servers.video-cloud.net/sv2servers.xml'
      }
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'ethernetgateway',
      href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/GWxxxxxxxxxx',
      name: 'MyQ HomeBridge',
      serial_number: 'GWxxxxxxxxxx',
      state: {
        firmware_version: '1.6',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-09-18T22:56:56.9847833Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/GWxxxxxxxxxx/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [],
        updated_date: '2020-09-18T22:56:59.9952809Z'
      }
    }
  ]
}
[9/18/2020, 8:50:12 PM] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CGxxxxxxxxxx, gateway: GWxxxxxxxxxx).
[9/18/2020, 8:50:12 PM] [myQ] myQ API: Discovered device family hawkeyecamera: Garage Door Camera (serial number: TC-xxxx-xxxxxxx).
[9/18/2020, 8:50:12 PM] [myQ] myQ API: Discovered device family gateway: MyQ HomeBridge [Chamberlain myQ Home Bridge] (serial number: GWxxxxxxxxxx).
[9/18/2020, 8:50:12 PM] [myQ] myQ device family 'hawkeyecamera' is not currently supported, ignoring: Garage Door Camera (serial number: TC-xxxx-xxxxxxx).
[9/18/2020, 8:50:12 PM] [myQ] myQ device family 'gateway' is not currently supported, ignoring: MyQ HomeBridge [Chamberlain myQ Home Bridge] (serial number: GWxxxxxxxxxx).
[9/18/2020, 8:50:24 PM] [myQ] {
  count: 3,
  href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices',
  items: [
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'garagedoor',
      device_platform: 'myq',
      device_type: 'wifigaragedooropener',
      href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/CGxxxxxxxxxx',
      name: 'Garage Door',
      parent_device: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/GWxxxxxxxxxx',
      parent_device_id: 'GWxxxxxxxxxx',
      serial_number: 'CGxxxxxxxxxx',
      state: {
        attached_work_light_error_present: false,
        aux_relay_behavior: 'None',
        aux_relay_delay: '00:00:00',
        close: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/CGxxxxxxxxxx/close',
        command_channel_report_status: false,
        control_from_browser: false,
        door_ajar_interval: '00:00:00',
        door_state: 'closed',
        gdo_lock_connected: false,
        invalid_credential_window: '00:00:00',
        invalid_shutout_period: '00:00:00',
        is_unattended_close_allowed: true,
        is_unattended_open_allowed: true,
        last_status: '2020-09-19T00:49:14.2664737Z',
        last_update: '2020-09-18T23:38:05.6490848Z',
        max_invalid_attempts: 0,
        online: true,
        open: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/CGxxxxxxxxxx/open',
        passthrough_interval: '00:00:00',
        report_ajar: false,
        report_forced: false,
        rex_fires_door: false,
        use_aux_relay: false
      }
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'hawkeyecamera',
      device_platform: 'myq',
      device_type: 'hawkeyecamera',
      href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/TC-xxxx-xxxxxxx',
      name: 'Garage Door Camera',
      serial_number: 'TC-xxxx-xxxxxxx',
      state: {
        last_event: 'MotionDetected',
        last_status: '2020-09-19T00:09:33Z',
        last_update: '2020-09-19T00:09:33Z',
        links: {
          events: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/TC-xxxx-xxxxxxx/events',
          stream: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/TC-xxxx-xxxxxxx/stream'
        },
        online: true,
        online_change_time: '2020-09-09T23:38:38Z',
        servers: 'https://v2servers.video-cloud.net/sv2servers.xml'
      }
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'ethernetgateway',
      href: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/GWxxxxxxxxxx',
      name: 'MyQ HomeBridge',
      serial_number: 'GWxxxxxxxxxx',
      state: {
        firmware_version: '1.6',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-09-18T22:56:56.9847833Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xx/devices/GWxxxxxxxxxx/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [],
        updated_date: '2020-09-18T22:56:59.9952809Z'
      }
    }
  ]
}
`

**Comment by hjdhjd** [comment]
Thanks...I captured it, and deleted the comment out of an abundance of caution for privacy.

**Comment by hjdhjd** [comment]
Can you also elaborate on what the model of the camera you have?

**Comment by Zsoldier** [comment]
No clue.  It's built into the opener.

**Comment by hjdhjd** [comment]
What's the model number of the opener.

**Comment by Zsoldier** [comment]
B6765

**Comment by hjdhjd** [comment]
Can you ping me on Discord? You can access it off the homepage for this plugin.  Let's discuss next steps there. I'd love to add support for it this weekend. Thanks!

**Comment by hjdhjd** [comment]
Putting this one on hold...we need someone to reverse engineer what URL myQ is requesting to display live video. Otherwise, I’ve got most of the plumbing ready to go for this one. As I mentioned in another thread...someone’s going to need to defeat / workaround certificate pinning in the myQ app to sniff the traffic and decode what’s going on. 

Once we’ve got the traffic decoded, I can provide support for it here. The best vector for doing so is probably on Android due to the challenges in jail breaking on iOS. 

Doing any of the above is well beyond the scope of what I’m comfortable doing...but if someone wants to take it on, happy to apply whatever we learn from that effort to adding functionality to this plugin.
