### ISSUE TITLE
Obstructed detection as a separate device. 

### ISSUE THREAD

**Issue by fr3nch13** [hjdhjd/homebridge-myq#1060]
**Is your feature request related to a problem? Please describe:**
Kind of. With the HomeKit native MyQ, it shows the state of the garage door as either open/opening/closed/closing, but also shows if it’s obstructed, like if the ir sensor is being blocked. 
However, you can’t setup an automation based on the obstructed state. 

**Describe the solution you'd like:**

It would be nice to expose the obstructed state as a separate device in HomeKit. Something like a sensor with a tripped state, or a dummy switch that is turned on if obstruction is detected, then times out after like 30 seconds or something. That way we can setup automations using the “A sensor detects something”, or the “An accessory is controlled”. 

I personally would like to have this so I can trigger an automation if my garage door is open, and something triggers that sensor, like someone walking into/out of my garage. 

I’m currently doing it with motion sensor from a camera in the garage, but it throws a lot of false-positives as it triggers on any motion. 

**Describe alternatives you've considered:**

Maybe try to build my own trigger with standalone beam sensor and a raspberry pi, and make a homebridge plugin. 

**Additional context:**

**Comment by hjdhjd** [comment]
Thanks for the suggestion - I'll consider this in the future...has some fun implications. Thanks again.
