### ISSUE TITLE
Garage camera as a separate device

### ISSUE THREAD

**Issue by fr3nch13** [hjdhjd/homebridge-myq#1061]
**Is your feature request related to a problem? Please describe:**

Some of the newer garage doors come with a built in camera hanging off the bottom. 

**Describe the solution you'd like:**

Expose that camera as a separate device in HomeKit. 

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
Please don't open duplicate requests that have been made many times previously. Thanks.
