### ISSUE TITLE
Camera Support

### ISSUE THREAD

**Issue by aw-0** [hjdhjd/homebridge-myq#1063]
**Is your feature request related to a problem? Please describe:**
As a lot of users have suggested, myQ camera support would be wonderful in this plugin.

**Describe the solution you'd like:**
The ability to view myQ cameras in the Home App, similar to a regular doorbell/security camera

**Describe alternatives you've considered:**
No alternatives exist to this problem.

**Additional context:**
I've noticed, @hjdhjd, that you're more than happy to work on this issue but need the certificate pinning of the iOS app to sniff the camera requests. I have successfully pinned the certificates on my device and have access to some camera info, but not the exact stream URL just yet.

The domain that houses a large majority of the camera information seems to be `tendplatform.com`, which looks to be run by `tendinsights.com` (there's a myQ partnership listed on that site). I have also noticed `SeeDonk / seedonk.com` mentioned in the headers of some requests, however not sure of the relevance. Here's an example response from a [camera info API request](https://pastebin.com/BmPRC31i). I have obviously redacted any personal info/sensitive IDs, but anyone should be able to get a gist of the general response. 

The response indicates that the video is H264 & is potentially streamed over RTP? I don't have much experience in video streaming, however, I did not notice any other requests that directly mentioned a RTP stream URL. This may be because my proxy (Charles Proxy) only supports HTTPS and can't sniff for any other request type.

Additionally, I noticed that `devices.myq-cloud.com` returns a "Camera" device, with `links.stream` returning a stream URL. I assume you already have messed with this in the past, as it's available in the general my-Q API. I tried myself, however, whenever I went to visit any other URLs besides the `/devices` page, I kept getting a `-99` return code and told to contact customer care in the JSON response.

Curious if you have any insight on this. More than happy to send over additional info from my rooted device.

P.S. -- would comment on this under an older issue, but seems as if Github has locked them all randomly in the past few hours. More than happy to close this issue and move to another one if I missed something :)

**Comment by hjdhjd** [comment]
First, thanks for the post and sharing what you’ve learned. Tend and Seedonk are the same company (Tend used to be known as Seedonk). Happy to work with you on this further - if you’d like to DM me on the Homebridge Discord, we can discuss a bit further. Thanks for the outreach.

PS: old issues are intentionally locked now to prevent necroposting. 😄
