### ISSUE TITLE
Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by kaduffey** [hjdhjd/homebridge-myq#1072]
**Describe The Problem:**
a single error on 5/3 when the only plugin running was MyQ - stream of memory errors on 5/11. Fujitsu Plugin added after errors appeared

**To Reproduce:**
none known

**Logs:**
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[5/3/2023, 4:29:38 PM] [DuffmyQ] Paulson Garage two: Opening.

then yesterday a bunch of them
[5/11/2023, 4:58:25 PM] [DuffmyQ] Paulson Garage two: Closed.
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 childBridgeStatusUpdate listeners added to [HomebridgeIpcService]. Use emitter.setMaxListeners() to increase limit
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:5235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
[5/11/2023, 7:41:29 PM] [DuffmyQ] Paulson Garage two: Opening.

 
**Homebridge Configuration:**

 "bridge": {
        "name": "Homebridge",
        "username": "***",
        "port": 51368,
        "pin": "*******",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "my email",
            "password": "*********",
            "name": "DuffmyQ",
            "platform": "myQ"
        },
        {
            "name": "Fujitsu AC",
            "username": "my email",
            "password": "***********",
            "region": "us",
            "offMode": "fan",
            "powerfulModeSwitch": false,
            "economyModeSwitch": false,
            "energySavingFanSwitch": false,
            "platform": "FujitsuHVAC",
            "_bridge": {
                "username": "********",
                "port": 56107
            }
        }
    ]
}

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16
* **Homebridge-myQ Plugin Version**: 2.11.1 running on a Ionexx XOME Debian based Orange Pi
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**

**Comment by hjdhjd** [comment]
Thanks for the report: I'd like to verify first that it's the myQ plugin...can you disable the other plugin and see if the issue still occurs?

**Comment by kaduffey** [comment]
please note, as stated in the report, I was getting the error BEFORE i
loaded the fujitsu plugin (that is also in a child bridge).

**Comment by kaduffey** [comment]
This was corrected with this latest MyQ point release last week. The errors stopped after the last update.  It possibly could have also been the HB UI update that both came last week.  Can you confirm if you addressed this?

**Comment by hjdhjd** [comment]
Nope. As I said, I don't believe this is an issue with homebridge-myq, but I'm open to the possibility if there's a reproducible scenario. Glad the issue is resolved. Best of luck.
