### ISSUE TITLE
Device not showing with Node 16

### ISSUE THREAD

**Issue by yuletide** [hjdhjd/homebridge-myq#1073]
**Describe The Problem:**

Apologies if I missed something obvious but I've just set this up for the first time and even though my node version is lower than required (Node 18 is not supported by this old server) the plugin seemed to load fine without error. However, no devices are appearing in the plugin config screen. Is there anything else I could try to get things working? I'm getting no errors.

**To Reproduce:**

**Logs:**

```
[5/15/2023, 3:12:42 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/15/2023, 3:12:42 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 19498
[5/15/2023, 3:12:42 PM] Loaded config.json with 0 accessories and 2 platforms.
[5/15/2023, 3:12:42 PM] Loaded 0 cached accessories from cachedAccessories.
[5/15/2023, 3:12:42 PM] ---
[5/15/2023, 3:12:43 PM] Loaded plugin: homebridge-config-ui-x@4.50.4
[5/15/2023, 3:12:43 PM] Registering platform 'homebridge-config-ui-x.config'
[5/15/2023, 3:12:43 PM] ---
[5/15/2023, 3:12:43 PM] The plugin "homebridge-myq" requires Node.js version of >=18 which does not satisfy the current Node.js version of v16.20.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[5/15/2023, 3:12:44 PM] Loaded plugin: homebridge-myq@2.12.0
[5/15/2023, 3:12:44 PM] Registering platform 'homebridge-myq.myQ'
[5/15/2023, 3:12:44 PM] ---
[5/15/2023, 3:12:44 PM] Loading 2 platforms...
[5/15/2023, 3:12:44 PM] [myQ] Initializing myQ platform...
[5/15/2023, 3:12:44 PM] [myQ] Debug logging on. Expect a lot of data.
Setup Payload:
X-HM://xxx
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx │     
    └────────────┘     
                       
[5/15/2023, 3:12:44 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge) is running on port x.
[5/15/2023, 3:12:44 PM] [myQ] myQ API: Successfully connected to the myQ API.
[5/15/2023, 3:12:45 PM] [myQ] {
  accounts: [
    {
      created_by: 'uuid',
      id: 'uuid',
      max_users: { co_owner: 2, guest: 5 },
      name: "Home"
    }
  ]
}

```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "x,
        "port": 51176,
        "pin": "x",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "email": "x,
            "password": "x",
            "name": "myQ",
            "debug": true,
            "platform": "myQ"
        }
    ]
}
```

**Screenshots:**

<img width="782" alt="image" src="https://github.com/hjdhjd/homebridge-myq/assets/58695/6c75779f-1cab-4a54-9f22-2d666c78b53b">

**Environment:**

* **Homebridge Version:** Up To Date
[v1.6.1](javascript:void(0))
* **Node Version:** [16.20.0](https://homebridge.io/w/JTKEF)
* **Homebridge-myQ Plugin Version**: latest just installed
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple Macbook pro late 2011, running OS 10.13.6,

Accessing homekit from several other devices including a 2022 MBP and iphone 11
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Welcome to the community.

If the devices appear in the myQ app, they should show up in the plugin. Do the garage door openers appear in the native myQ app, with the same username and password?

The plugin is pretty straightforward and set-and-forget.

Cheers.

**Comment by yuletide** [comment]
Thanks! Yup we use the native myq app without issue using the same login
and pass.

**Comment by Sam-Spencer** [comment]
+1 on this issue. No devices and nothing showing in the logs for me either, except I'm running the latest stable version of node (18.16.something...).

I've also enabled debug logging, but the only statements printed to the log are:

```
[myQ] Initializing myQ platform...
[myQ] Debug logging on. Expect a lot of data.
[myQ] myQ API: Successfully connected to the myQ API.
```

After that, its radio silence. Not even statements for failed pings, looking for a device maybe?

**Comment by tbelcher** [comment]
Similar issue for me.  Running node.js v16.13.0 and it was working fine until my hub upgraded to tvOS16.5.  Now the garage door only shows as "updating" in the home app.  It does show the correct status in the Homebridge status page however.

**Comment by hjdhjd** [comment]
> Similar issue for me. Running node.js v16.13.0 and it was working fine until my hub upgraded to tvOS16.5. Now the garage door only shows as "updating" in the home app. It does show the correct status in the Homebridge status page however.

Please don’t hijack someone else’s support thread without the same exact symptoms. If you have an issue that you’d like support for, please open a new issue. Thanks.

**Comment by hjdhjd** [comment]
> Thanks! Yup we use the native myq app without issue using the same login and pass. Screenshot of the opener in the app: ![img](https://github.com/hjdhjd/homebridge-myq/assets/58695/14f9b567-bd8c-4b48-8e40-364fa4d3c8c6) Any other logging or troubleshooting I could try?

As far as I can see, there’s not a plugin issue here…we show whatever the myQ API gives us. You’re welcome to try earlier versions of the `homebridge-myq` and see if the issue disappears…there’ve been a few updates over the past few weeks, but in general, there hasn’t been a core change to this plugin in quite some time.

I did also notice you’ve got a bunch of guests configured in the snippet you posted above - are you sure you’re using an account and password that has access to the openers in question?

Otherwise, I’m afraid we’re at the end of what I can offer support for here. I can’t reproduce this issue, and I don’t see any problem from an API perspective. I’d check:

1. If you’re definitively using the same exact username and password (which you have above).
2. Potentially checking permissions and see if there’s something specific going on if you’re using guest modes, etc. I don’t think this would be an issue, so this is a stretch…but who knows.
3. Trying prior versions of homebridge-myq…I’d go back as far as v2.8.3 and see.

Welcome to hear what you discover…would love to help you get up and running.

**Comment by hjdhjd** [comment]
> +1 on this issue. No devices and nothing showing in the logs for me either, except I'm running the latest stable version of node (18.16.something...).
> 
> I've also enabled debug logging, but the only statements printed to the log are:
> 
> ```
> [myQ] Initializing myQ platform...
> [myQ] Debug logging on. Expect a lot of data.
> [myQ] myQ API: Successfully connected to the myQ API.
> ```
> 
> After that, its radio silence. Not even statements for failed pings, looking for a device maybe?
> 
> @hjdhjd I also experience no issues with the native myQ app. Garage door shows up there and is functioning just fine. Same as is shown in @yuletide's screenshot.

Try the same points as above…as I stated, there’s not much I can do here without being able to recreate the issue myself. If you’re able to login to the API, you’re in good shape, conceptually. Give the above a shot and see what happens. Curious to see if there are commonalities in your setups. Was this working for either of you before and only recently stopped?

**Comment by yuletide** [comment]
This is a great call and I’ll check accounts again once I’m back home but I
think they could be the culprit — we have various account levels and I was
signed in with not an admin account.

**Comment by yuletide** [comment]
I will verify tomorrow and close if that resolves things which it likely will

**Comment by yuletide** [comment]
Working, thanks for the help!
