### ISSUE TITLE
https://partner-identity.myq-cloud.com/api/Account/null Error: 400 Bad Request

### ISSUE THREAD

**Issue by brooklyngithub** [hjdhjd/homebridge-myq#1078]
**Describe The Problem:**
When the garage door opens, my Lutron lights don't come up because of a 400 Bad Request
This is a new issue, it was working before

**To Reproduce:**
Open the garage with the MyQ app
The garage does open
Check the logs, they show a 400 Bad Request

**Logs:**
[09/07/2023, 11:45:59] [myQ] myQ API: https://partner-identity.myq-cloud.com/api/Account/null Error: 400 Bad Request
[09/07/2023, 11:45:59] [myQ] myQ API: Unable to complete the OAuth login redirect.

**Homebridge Configuration:**

{
    "bridge": {
        "name": "Homebridge 6A38",
        "username": "bbbbbb",
        "port": 51704,
        "pin": "cccccc",
        "advertiser": "avahi",
        "bind": [
            "eth0",
            "wlan0"
        ]
    },
    "accessories": [
        {
            "name": "Tic",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 15000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Toc",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 15000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Humidity Low AC Reset",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 30000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "email": “xxxxxxx”,
            "password": “yyyyyyy”,
            "options": [
                "Disable.GW23001AFB59"
            ],
            "platform": "myQ"
        },
        {
            "name": "Nest",
            "access_token": "zzzzz",
            "structureId": "aaaaaa",
            "platform": "Nest"
        }
    ]
}

**Screenshots:**
![image](https://github.com/hjdhjd/homebridge-myq/assets/139067363/e446a5b5-6405-4bf6-927b-8511d1db02bd)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-myQ Plugin Version**: homebridge-myq v2.12.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version** : tvOS
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Occasional errors will occur, as stated in the documentation. This is an imperfect API, and the documentation clearly states this.

Nothing in this plugin deals with Lutron lights, sorry. Best of luck.

**Comment by brooklyngithub** [comment]
The lutron lights are controlled by appleTV
