### ISSUE TITLE
myQ API: Unable to complete the OAuth login redirect.

### ISSUE THREAD

**Issue by hujingtong1986** [hjdhjd/homebridge-myq#1088]
**Describe The Problem:**
[8/5/2023, 5:55:19 PM] [myQ] myQ API: https://partner-identity.myq-cloud.com/api/Account/null Error: 400 Bad Request
[8/5/2023, 5:55:19 PM] [myQ] myQ API: Unable to complete the OAuth login redirect.

**Homebridge Configuration:**
        {
            "email": "xxx",
            "password": "xxx",
            "name": "myQ",
            "debug": true,
            "platform": "myQ"
        }

**Screenshots:**

<img width="1083" alt="Screenshot 2023-08-05 at 6 02 17 PM" src="https://github.com/hjdhjd/homebridge-myq/assets/31831311/c7ace095-6b2d-4a35-9d08-05e851f5f8b0">

**Environment:**

* **Homebridge Version:** v1.6.1
* **Node Version:** [v18.15.0]
* **Homebridge-myQ Plugin Version**: v2.12.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Latest
* **Operating System and OS Version:** Synology920Plus

**Comment by hjdhjd** [comment]
Not a bug. Please read the documentation. Errors will happen on occasion.
