### ISSUE TITLE
Unable to acquire an OAuth access token

### ISSUE THREAD

**Issue by aharrod** [hjdhjd/homebridge-myq#1089]
Was working prior.  All of a sudden, I am unable to authenticate using verified credentials.  The myQ app works with the same credentials.

I changed the credentials twice, and contacted myQ support to ensure my account was not locked out, to no avail.

```
[myQ] Loaded homebridge-myq v2.12.0 child bridge successfully

[myQ] myQ API: Invalid myQ credentials given. Check your login and password.
[myQ] myQ API: Unable to acquire an OAuth access token.

last two repeat over and over.

```
{
            "email": "REDACTED",
            "password": "REDACTED",
            "name": "myQ",
            "_bridge": {
                "username": "0E:C1:AC:36:XX:XX", <--(PARTIAL REDACTION)
                "port": 364XX <--(PARTIAL REDACTION)
            },
            "platform": "myQ"
}

```
Homebridge Version: 1.6.1
Node Version: 18.17.0
Homebridge-myQ Plugin Version: 2.12.0
Apple Device and iOS / macOS / iPadOS / tvOS Version: various devices, not getting that far tho
Operating System and OS Version: Raspbian Debian GNU/Linux Bullseye (11)

**Comment by mbierman** [comment]
For what it is worth, I'm seeing this as well. I have confirmed that my username and password are correct. (and it would have been weird if they suddenly didn't work because I haven't changed them lately.) 

```
[myQ] myQ API: Invalid myQ credentials given. Check your login and password.
[8/7/2023, 11:00:34 PM] [myQ] myQ API: Unable to acquire an OAuth access token.
```

**Comment by jrose323** [comment]
I'm having the same issue. Confirmed my username and password is correct as well.

**Comment by tcmac773** [comment]
Can confirm I'm also getting this error.
[8/8/2023, 12:21:00 PM] [myQ] myQ API: https://partner-identity.myq-cloud.com/api/Account/null Error: 400 Bad Request
[8/8/2023, 12:21:00 PM] [myQ] myQ API: Unable to complete the OAuth login redirect.

Logged out and back in on the app to make sure my username/password is correct.

**Comment by aharrod** [comment]
I’m thinking MyQ changed their API again. Hoping this can be resolved soon.

**Comment by hjdhjd** [comment]
They haven’t. myQ is just having backend issues.

As noted in the documentation - **myQ API errors will happen**. Cheers.

**Comment by aharrod** [comment]
Will happen is very different than to the point of non functional. In any case, appreciate the confirmation of a MyQ backend issue and hope they resolve soon.

**Comment by hjdhjd** [comment]
> Will happen is very different than to the point of non functional. In any case, appreciate the confirmation of a MyQ backend issue and hope they resolve soon.

No worries, but for clarity: that’s incorrect. If the myQ backend API has issues, things will *always* be nonfunctional when it comes to myQ.
