### ISSUE TITLE
myQ API Error 400 Bad Request

### ISSUE THREAD

**Issue by Dbot00** [hjdhjd/homebridge-myq#109]
Hi, just wanted to alert that the unable to authenticate errors seem to be back.  I've been experiencing the issue for 3 days now.  I'm running the latest version of the plugin and homebridge. I've uninstalled and reinstalled the plugin and restarted Homebridge.  The MyQ app is able to open the garage door.  I've read how the API is ever updating and flaky but since this behavior has been constant for multiple days (for me) I thought it might be worth reporting.

**Comment by whreams** [comment]
Maybe network related?
I’m located in the US CTZ and all is good here. Logs look clean.

**Comment by hjdhjd** [comment]
Thanks for reporting this. I've not seen an issue other than the occasional flakiness of the API, as it always has been. Can you elaborate in more detail on what you mean by *constant?*?

**Comment by Dbot00** [comment]
Hi, I'm in the US, same time zone.  I'm seeing the 400 log message, followed by the unable to auth log message every 3-4 seconds.....DOH!!!  Crap, I just had an aha moment thinking about your reply and what info I could provide.  My server is connected to a VPN and has been the whole time I've been running Homebridge and the MyQ plugin without issue.  I just disconnected it from the VPN and the logs immediately went clean.  Sorry for the false alarm, I love your plugin and didn't want to raise an issue without due diligence...it just didn't occur to me that the issue could be VPN related (perhaps blocking Canada IPs since it's not my location?) since its been working all this time.  Thanks for the quick response, my bad for the false issue.

**Comment by hjdhjd** [comment]
It happens. :smile:
