### ISSUE TITLE
Newer versions of MyQ plugin don’t work

### ISSUE THREAD

**Issue by cjwyche95** [hjdhjd/homebridge-myq#1093]
**Describe The Problem:**
I have been using the MyQ plugin successfully for over a year, but versions newer than 2.9 will not install successfully in my Hoobs box. Just tried version 3.0 with the same result, so reverted back to 2.9 again.  Any suggestions would be appreciated.  

**To Reproduce:**
Download and install newer version than 2.9 onto my hoobs box and it fails to install and connect to APIs.

**Logs:**
I don’t have the logs available at this time with the errors.  Loaded version 2.9 now and works fine.

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Sorry, I provide no support for HOOBS. You'll have to visit that project and ask for support there. homebridge-myq is a Homebridge plugin. HOOBS leverages Homebridge but it's their own thing. Thanks.
