### ISSUE TITLE
Hello, with the latest version I'm not getting any settings showing up for the plugin--it goes to the usual Myq page but there's no selectable settings options. Things are working, but I just bought a video keypad and was wondering if there's a way to add that video feed to HomeKit. Any help would be appreciated thanks! I'm using node version 18.17.1.

### ISSUE THREAD

**Issue by sklemow** [hjdhjd/homebridge-myq#1094]
**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Closing this issue. Please either use the Homebridge Discord or fully complete the support template. Thanks.
