### ISSUE TITLE
Issue configuring plugin after update

### ISSUE THREAD

**Issue by connorgallopo** [hjdhjd/homebridge-myq#1097]
**Describe The Problem:**
After updating to the newest Homebridge Config UX and updating MyQ plugin I was unable to edit the config, and my ignored devices started to show again.

To isolate the issue I decided to wipe the config for the plugin, uninstall the plugin, and reinstall.

After a fresh install and reboot I am unable to configure the plugin with the UX.

**To Reproduce:**
- Make sure UX and Plugin are up to date
- Uninstall plugin and create fresh config/wipe config
- Install plugin
- Open settings to see issue

**Logs:**
No relevant logs were found
**Homebridge Configuration:**
This is reproducible with a fresh config

**Screenshots:**
![image](https://github.com/hjdhjd/homebridge-myq/assets/21372032/7875941b-a797-480f-a6af-3d4ea6028db9)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v18.16.0
* **Homebridge-myQ Plugin Version**: LATEST
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**  Docker

**Comment by connorgallopo** [comment]
Update: I downgraded homebridge-ui-x to the release before current and the issue is resolved. Seems like it is a regression from that update.

**Comment by hjdhjd** [comment]
There's an issue [here](https://github.com/homebridge/homebridge-config-ui-x/issues/1527) on the Homebridge webUI regression. Feel free to add your own data points so we can get this tracked down. Thanks!
