### ISSUE TITLE
Plugin issues excessive DNS requests

### ISSUE THREAD

**Issue by mpherg** [hjdhjd/homebridge-myq#1098]
**Describe The Problem:**
The plugin issues an excessive number of DNS resolution requests, especially for accounts.myq-cloud.com and devices.myq-cloud.com. For instance, on my network of ~40 devices, these domains account for ~30% of all DNS resolution requests (26,701 requests in a single 24 hour period) from a single homebridge installation.

Admittedly this is a low-priority problem, but this noise makes it more difficult to analyze "real" DNS traffic on my network.

**To Reproduce:**
Run the homebridge-myq plugin and configure it with proper myq credentials and devices.

**Logs:**
n/a

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge 8CDA",
        "username": "<redacted>",
        "port": 51883,
        "pin": "<redacted>",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "<redacted>",
            "password": "<redacted>",
            "name": "myQ",
            "debug": false,
            "_bridge": {
                "username": "<redacted>",
                "port": 47295
            },
            "platform": "myQ"
        }
    ],
    "disabledPlugins": []
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.1
* **Node Version:** v18.16.0
* **Homebridge-myQ Plugin Version**: v3.2.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 16.6
* **Operating System and OS Version:** Raspbian v1.0.38

**Comment by hjdhjd** [comment]
This plugin does not have an excessive number of DNS requests - it produces exactly as many as I've designed it to. 😄

It's the way a polling interface to the myQ API like this works. It's also been asked-and-answered previously in prior issues, I'll refer you to searching through prior issues rather than re-answering it here.

Best of luck.

**Comment by mpherg** [comment]
Thank you for your prompt response, and sorry for not finding the prior issues; I'll go take a look. I'm a C++ developer, so js/ts is a bit foreign to me. Generally in C/C++ we resolve the DNS name once and cache it for some long-ish duration. Perhaps there's a node/OS configuration I can find.

Thanks for the plugin -- works great.
