### ISSUE TITLE
Please address https://github.com/hjdhjd/homebridge-myq/issues/1100

### ISSUE THREAD

**Issue by adamcnaglich** [hjdhjd/homebridge-myq#1101]
**Is your feature request related to a problem? Please describe:**
My garage door reads as offline. It would seem this is due to something with the API??

**Describe the solution you'd like:**
I'd like to know if a solution is available and can be implemented. I'm no developer.

**Describe alternatives you've considered:**
I've tried restarting the child bridge and that seems to work for a few minutes I think.

**Comment by hjdhjd** [comment]
This isn't a feature request.
