### ISSUE TITLE
Cannot Login Into MyQ 

### ISSUE THREAD

**Issue by bluskye** [hjdhjd/homebridge-myq#1102]
**Describe The Problem:**
Updated MyQ plugin.  

Attempted to login I receive this error:
Unable to login to the myQ API.
Please check your email address and password.
myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.

**To Reproduce:**

1. Removed plugin
2. Reinstalled plugin
3. Enter my credentials
4. Hit Log In button

**Logs:**

Show the Homebridge logs here.
Remove any sensitive information.

[9/8/2023, 5:21:52 PM] [Homebridge UI] [homebridge-myq] Incoming Request: /getErrorMessage
[9/8/2023, 5:21:52 PM] [Homebridge UI] [homebridge-myq] Incoming Request: /getDevices
[9/8/2023, 5:21:53 PM] [Homebridge UI] [homebridge-myq] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable 

**Homebridge Configuration:**

None, the plugin cannot log in

**Screenshots:**

![266742336-bed8aef9-711c-43a0-900b-3baf168da7d9](https://github.com/hjdhjd/homebridge-myq/assets/3529574/adbfea93-eb0f-4950-82e0-7fd5f9d51dc6)

**Environment:**

* **Homebridge Version**: 1.6.1
* **Node Version**: 18.17.1
* **Homebridge-myQ Plugin Version**: 3.3.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version**: IOS 16.6.1
* **Operating System and OS Version**:  Docker Ubuntu Jammy Jellyfish (22.04.2 LTS)

**Comment by mojtabacazi** [comment]
same here, hasn't been working for past few days

**Comment by xenonaxel** [comment]
Just started happening to me 15 min ago.

**Comment by GabeShack** [comment]
Same

**Comment by bluskye** [comment]
Im not crazy!

**Comment by hjdhjd** [comment]
The myQ server end is either experiencing issues in your geography, or you're entering invalid credentials. Other users have been having challenges in some geographies...it should resolve itself in a little time, as it typically does. There's not much for me to do on the plugin end I'm afraid - we're dealing with a fragile API endpoint. You're welcome to check the Discord for other suggestions as well. Cheers.

**Comment by TottiUno** [comment]
Having the same issue what geography issues exist, seems to be more of an authentication issue.

**Comment by GabeShack** [comment]
Since the actual myq app logs in and works then it seems to be an api tie in issue with authentication. Their app still allows logins.

**Comment by hjdhjd** [comment]
https://github.com/hjdhjd/homebridge-myq/issues/1103#issuecomment-1712372159
