### ISSUE TITLE
/nonexistent error

### ISSUE THREAD

**Issue by doctorkb** [hjdhjd/homebridge-myq#1105]
**Describe The Problem:**

Tried to update today. Received this error:
```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
```

**To Reproduce:**

Click "Update" in HomeBridge. Click "OK" with release notes modal.

**Logs:**

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
```

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-myQ Plugin Version**: attempting update to 3.4.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** n/a
* **Operating System and OS Version:** Debian 12.1

**Comment by hjdhjd** [comment]
Thanks for the report but this really belongs in the homebridge-config-ui-x project. I’ve got nothing to do with how you install homebridge-myq. 😀 I would suggest opening an issue there.

Alternatively you can uninstall and reinstall the plugin. Your configuration information should be saved. Best of luck.

**Comment by doctorkb** [comment]
I've been running HomeBridge for a couple of years, with several plugins.  This is the first time any update has thrown this error, so it seems more likely an issue with your build files.  Something that homebridge-config-ui-x has nothing to do with.

I started poking around a bit further and it seemed to be an issue that my homebridge user's home directory was set to /nonexistent and npm felt the need to create files in the home directory.  Not sure why it never needed this before, but setting up a home directory for the homebridge user resolved it.

**Comment by hjdhjd** [comment]
Glad to hear you solved it - but I doubt it has anything to do the build process for this package - it’s automated and has been unchanged in years. Could be a config issue or perhaps a version of npm or node. Regardless - best of luck. Cheers.
