### ISSUE TITLE
Unable to login for about a week (Unable to login to the myQ API. Please check your email address and password.)

### ISSUE THREAD

**Issue by codydalerodgers** [hjdhjd/homebridge-myq#1110]
**To Reproduce:**
Upon logging in, I receive the error message "Unable to login to the myQ API.
Please check your email address and password." I have used this plugin for about a year without issue but for the past week or so I have not been able to connect. There have been no changes to my account on the MyQ side and I can login without issue on their app. The following is after trying to login:

**Logs:**

[17/09/2023, 20:49:52] [Homebridge UI] Homebridge log truncated by admin.
[17/09/2023, 20:50:091
[Homebridge UI] [homebridge-myq] Incoming Request: /getDevices
[17/09/2023, 20:50:091
[Homebridge UI] [homebridge-myq] Unable
Unable to retrieve the list o
f myl devices from the myl API.
[17/09/2023, 20:50:091 [Homebridge UI] [homebridge-myg] TypeError: Cannot read proper ty 'getRandomvalues' of undefined
at getRandomvalues (file:///us/local/lib/node_modules/homebridge-myg/node_module
s/pkce-challenge/dist/index.js:10:19)
at random (file:///usr/local/lib/node_modules/homebridge-myg/node_modules/pkce-ch
allenge/dist/index.js:19:25)
at generateVerifier (file:///us/local/lib/node
_modules/homebridge-myq/node_modul
es/pkce-challenge/dist/index.js:32:12)
at pkceChallenge (file:///us/local/lib/node_modules/homebridge-myq/node_modules/

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**
![image](https://github.com/hjdhjd/homebridge-myq/assets/11512464/6a53a1aa-396a-40aa-8c07-2fdf65e187c6)
![image](https://github.com/hjdhjd/homebridge-myq/assets/11512464/4b54ac09-26ef-4cae-8e54-4e090711a544)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v14.16.0
* **Homebridge-myQ Plugin Version**: 3.4.1
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 14 Pro Max iOS 17.0
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Thanks for the report. A few things:

* You're running on Node 14 - anything below Node 18 is unsupported.
* You're running a beta version of iOS - also unsupported.

I'd start with updating your version of Node to a supported version. Node 14 has been out of support for some time, and Node 16 was EOL as of last week. I only support current LTS versions of Node. Best of luck.
