### ISSUE TITLE
Support for MyQ Video Keypad

### ISSUE THREAD

**Issue by EddieDaYankee** [hjdhjd/homebridge-myq#1112]
**Is your feature request related to a problem? Please describe:**
 I recently purchased the MyQ Video Keypad and am unable to see the video feed in HomeKit.

**Describe the solution you'd like:**
I would like to be able to view my video keypad’s video feed in HomeKit via HomeBridge. In addition, it would be great to get the same alerts as in the MyQ app like user specific alerts when a certain code is entered to open the garage door.

**Describe alternatives you've considered:**
I have not considered any alternatives. 

**Additional context:**
I am happy to assist in any beta testing.

**Comment by hjdhjd** [comment]
This has been asked and answered previously. I may add support in the future, but this isn’t a priority. In the future, please look at previously closed issues before opening a new one on an identical topic. Appreciate the interest.
