### ISSUE TITLE
mqtt username and password

### ISSUE THREAD

**Issue by radhoo2k10** [hjdhjd/homebridge-myq#1114]
**Is your feature request related to a problem? Please describe:**
Need to be able to enter mqtt username and password

**Describe the solution you'd like:**
in settings enter username and password for the mqtt broker

**Describe alternatives you've considered:**
none

**Additional context:**
Add username and password here:
![image](https://github.com/hjdhjd/homebridge-myq/assets/78762281/432502ed-044e-4500-ae17-b2589258fc76)

**Comment by hjdhjd** [comment]
This already exists. 

https://github.com/hjdhjd/homebridge-myq/blob/main/docs/MQTT.md#how-to-configure-and-use-this-feature

**Comment by radhoo2k10** [comment]
> This already exists.
> 
> https://github.com/hjdhjd/homebridge-myq/blob/main/docs/MQTT.md#how-to-configure-and-use-this-feature

Ah. Totalt missed that. 😂
