### ISSUE TITLE
Unable to access the OAuth authorization endpoint

### ISSUE THREAD

**Issue by craigharman** [hjdhjd/homebridge-myq#1115]
**Describe The Problem:**
Plugin has been working for over a year. Last few weeks I started getting the error:

myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=<REDACTED>&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 403 Forbidden
[10/5/2023, 8:15:34 PM] [Garage Door] myQ API: Unable to access the OAuth authorization endpoint.

Have seen multiple people reporting the same issue: https://www.reddit.com/r/homebridge/comments/u4g5ek/myq_plugin_unable_to_access_the_oauth/

**To Reproduce:**
Have plugin running in Homekit with username and password entered.

**Logs:**
```
myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=<REDACTED>&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 403 Forbidden
[10/5/2023, 8:15:34 PM] [Garage Door] myQ API: Unable to access the OAuth authorization endpoint.
```

**Homebridge Configuration:**

```json
{
            "email": <removed>
            "password": <removed>,
            "name": "Garage Door",
            "myQRegion": "east",
            "platform": "myQ"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.1
* **Node Version:** 18.15
* **Homebridge-myQ Plugin Version**: v3.4.1
* **Apple Device and iOS / macOS / iPadOS / tvOS Version: iPhone and OS X 14.0
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
This isn’t a bug. It’s just the myQ API quirkiness and reliability challenges it has from time to time. This is well documented in many prior issues, as well as in the README for this plugin.
