### ISSUE TITLE
API Login Failures

### ISSUE THREAD

**Issue by dashdriverdan** [hjdhjd/homebridge-myq#1117]
**Describe The Problem:**
Since about 1700 UTC yesterday Homebridge-myq has been unable to log in, producing a variety of errors. HomeAssistant's MyQ implementation failed almost simultaneously. 

https://github.com/home-assistant/core/issues/101763

**To Reproduce:**
Alternatively: wait, or restart Homebridge. 

**Logs:**
[myQ] myQ API error: Invalid myQ credentials given: Check your username and password. If they are correct, the myQ API may be experiencing temporary issues. 
[myQ] myQ API error: Temporary myQ API server-side issues encountered: 429 - Too Many Requests.

**Homebridge Configuration:**

```json
"platforms": [
        {
            "name": "myQ",
            "platform": "myQ",
            "email": "redacted@redacted",
            "password": "redacted"
        }
    ]
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.1
* **Node Version:** v18.15.0
* **Homebridge-myQ Plugin Version**: v3.4.1
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPad Mini 6-Generation (MK893VC/A), iPadOS 16.6
* **Operating System and OS Version:** Synology DSM [7.2-64570](tel:7264570) Update 1

**Comment by dreagleeyes** [comment]
I am seeing this also

**Comment by hjdhjd** [comment]
Yep I’m seeing it too…that said: while I am sure this is well intentioned: **please do not open these issues related to API failures.** As [documentation](https://github.com/hjdhjd/homebridge-myq#things-to-be-aware-of) they will happen on occasion…sometimes for hours or a day or so. If there’s a long-standing persistent problem that’s lasting several days at a time, then feel free to.

I use this plugin daily as well…I see the issues too. When there’s something that’s addressable from my end versus the myQ API end, I will.

Thanks.

**Comment by shadowpuck99** [comment]
i realize the documentation around API failures - but, given the issues MyQ has been having lately in Home Assistant - it seemed reasonable to open this issue.  Is it possible for the MyQ app to work perfectly fine and the API to not work?  Wouldn't that point to something that might need to be changed in the integration?

I realize this is now closed - but, it's a legit question I have about this.
Thank you for any time/assistance/feedback.

**Comment by hjdhjd** [comment]
There is no evidence that myQ has changed the API - please don’t come on the forums that I manage and curate and make declarative statements without meaningful technical evidence beyond “this works and that doesn’t”. That isn’t what is happening here, and this type of speculation, while I’m sure well-intentioned, is unhelpful and creates more confusion.

**Comment by haywiremk** [comment]
> There is no evidence that myQ has changed the API - please don’t come on the forums that I manage and curate and make declarative statements without meaningful technical evidence beyond “this works and that doesn’t”. That isn’t what is happening here, and this type of speculation, while I’m sure well-intentioned, is unhelpful and creates more confusion.

https://github.com/Python-MyQ/Python-MyQ/pull/22

There is a fix for this issue?

**Comment by hjdhjd** [comment]
That’s not an API issue, it’s a suspected new OAuth forwarding gateway issue/quirk that may or may not be the underlying culprit. I’ll also remind folks that a few weeks ago, when another round of issues came up, some suspected there may be a new user agent requirement in a very similar circumstance, also in the HA community, and ultimately, as it often tends to be the case, the issue is an underlying myQ infrastructure issue.

I know folks are well-intentioned here, but let’s see what some time brings. This isn’t my first rodeo with the API. 😄
