### ISSUE TITLE
Hoobs plugin stopped working 

### ISSUE THREAD

**Issue by dgcan75** [hjdhjd/homebridge-myq#1132]
**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version 3.4.3 *:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
I provide no support for HOOBS, you'll need to reach out to that team. Thanks.
