### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by imgaryshap** [hjdhjd/homebridge-myq#1133]
**Describe The Problem:**

I cannot log in at start-up.  I'm logging in just fine directly with the MyQ app.  Same email and password do not work here.  See screenshots.  Please note this used to work great.  I cannot pinpoint when it stopped functioning.  

**To Reproduce:**

Click "Start Custom Plugin UI" > enter MyQ login > get an error message

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

![Screenshot 2023-10-19 at 1 28 39 PM](https://github.com/hjdhjd/homebridge-myq/assets/16693444/612b9c01-fd77-4704-b5fc-a7691b46e2aa)
![Screenshot 2023-10-19 at 1 28 00 PM](https://github.com/hjdhjd/homebridge-myq/assets/16693444/b916cc4a-0da1-4f2e-88f5-d062f2fd0471)

**Environment:**

* **Homebridge Version:**   1.6.1
* **Node Version:**   18.16.1
* **Homebridge-myQ Plugin Version**:    3.4.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Macbook Pro 2019, OS Sonoma 14
* **Operating System and OS Version:**

**Comment by SeanathanVT** [comment]
Yeah, they (MyQ) fucked up the API stuff for third-party access, likely in an effort to get you to use their app (because ads). The Home Assistant plugin is experiencing the same problem.

**Comment by blakej** [comment]
@hjdhjd before closing this thread, please consider leaving it open as a discussion thread until this is better figured out and to allow everyone to exchange information and troubleshoot.

For myself, after nearly 48 hours of having the plugin disabled and checking in every 6-12 hours with a single API request, I am still getting 429, so the usual "wait a few hours" solution isn't working for everyone. I have no other integrations tied into myQ.

**Comment by anderfrank** [comment]
> @hjdhjd before closing this thread, please consider leaving it open as a discussion thread until this is better figured out and to allow everyone to exchange information and troubleshoot.
> 
> For myself, after nearly 48 hours of having the plugin disabled and checking in every 6-12 hours with a single API request, I am still getting 429, so the usual "wait a few hours" solution isn't working for everyone. I have no other integrations tied into myQ.

Same here. Had this plugin and Home Assistant integration disabled for over 24hrs and just tried the plugin and got login anomaly/error 429 right away. Thanks for nothing MyQ.

**Comment by tistou64** [comment]
Yeah same here.
I disabled the plugin in bridge.
This is the log I get now. 
From the issue return in the first instance, it seems that they changed the way to log in via the API maybe?

![image](https://github.com/hjdhjd/homebridge-myq/assets/59917196/bd2e9c13-e4e4-4c24-8590-c67d01597dd4)

**Comment by anderfrank** [comment]
Someone on Reddit posted this response they got from MyQ support:


"For the safety of our MYQ Customers we did disable the use of our MYQ app with non-authorized third party apps that do not have a partnership with us to be controlling our app."

**Comment by seer14** [comment]
I'm not seeing this error in my logs

[10/19/2023, 7:25:44 PM] [myQ] myQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device.

**Comment by blakej** [comment]
Mine finally reset enough to receive the login anomaly error, but it does seem that after three login anomalies, the fourth attempt moves back to 429. This coincides with the results @tistou64 showed earlier.

**Comment by lavarsicious** [comment]
@hjdhjd Happy to help debug/diagnose from my end. I can proxy/scrape API requests from the native ios app and compare with what this plugin is doing (assuming they're using the same endpoints) to at least figure out what the server is using to break the current implementation. 

I agree that the 429 is misleading as myQ apps making requests from the same ip address are not rate limited, could be a simple api key header or similar?

Either way, closing all of these duplicate issues without leaving at least one of them is causing you more harm than good.

**Comment by nuthintoholdback** [comment]
Experiencing the same issue after disabling the homebridge myq plugin last night (~21 hours ago) and attempting to migrate to a fresh install today. Glad to know I'm not the only one.

**Comment by hjdhjd** [comment]
While I appreciate folks want to help or discuss - this is not the place for it. You’re welcome to use the myQ channel on the Homebridge Discord, otherwise, please do not continue adding to a already long series of messages stating the obvious: all myQ plugins / solutions out there need to continue to evolve to address the changing landscape.
