### ISSUE TITLE
Allowing People To Use Their Own API On A Node Server For Your Plugin

### ISSUE THREAD

**Issue by JEMcats** [hjdhjd/homebridge-myq#1137]
**Is your feature request related to a problem? Please describe:**
I want to use my node.js server to host the api server, can I do this?

**Describe the solution you'd want: 

I want to use my node server for the api.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
I’m unlikely to implement this, but stay tuned for more…
