### ISSUE TITLE
I have Chamberlain Lights!

### ISSUE THREAD

**Issue by ahnyerkeester** [hjdhjd/homebridge-myq#115]
My garage door open came with switches that use the garage door opener as a hub. I have two lamps plugged into them and would LOVE to help you develop support for them.

Hit me up!

**Comment by hjdhjd** [comment]
Terrific. First thing you can do is post your logs when you startup Homebridge. I’m looking for all the lines at the beginning that start with myQ. Let’s see what the plugin is already detecting. Thanks!

**Comment by ahnyerkeester** [comment]
Okay, here ya go. You can see that it detects the switches but ignores them:

`9/17/2020, 9:53:04 AM [Garage Door] myQ API: Successfully connected to the myQ API.`
`9/17/2020, 9:53:04 AM [Garage Door] myQ API: Discovered device family gateway: Garage Door [Chamberlain WiFi GDO AC] (serial number: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] myQ API: Discovered device family garagedoor: Garage Door Opener (serial number: CG0850122173, gateway: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] myQ API: Discovered device family lamp: Living Room Lamp (serial number: CG06A000A89A, gateway: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] myQ API: Discovered device family lamp: Living Room Light (serial number: CG06A000A811, gateway: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] Garage Door Opener: Adding garagedoor device to HomeKit: Garage Door Opener (serial number: CG0850122173, gateway: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] myQ device family 'lamp' is not currently supported, ignoring: Living Room Lamp (serial number: CG06A000A89A, gateway: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] myQ device family 'lamp' is not currently supported, ignoring: Living Room Light (serial number: CG06A000A811, gateway: GW0A00027F14).`
`9/17/2020, 9:53:04 AM [Garage Door] Garage Door Opener: Closed.`

**Comment by hjdhjd** [comment]
Terrific. Next thing is - enable debug logging (it’s under advanced options in the webUI)...and post the JSONs that get logged. Feel free to scrub it for sensitive material. The same JSONs will continue to get logged every few seconds...that’s what I need.

Happy to add the support for it in the next few days.

**Comment by ahnyerkeester** [comment]
Debugging enabled. Where are the JSONs located?

**Comment by hjdhjd** [comment]
Homebridge logs.

**Comment by ahnyerkeester** [comment]
I believe this is what you're looking for?

```
9/17/2020, 12:45:51 PM [Garage Door] {
  count: 4,
  href: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices',
  items: [
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'wifigdogateway',
      href: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/GW0A0XXXXF14',
      name: 'Garage Door',
      serial_number: 'GW0A0XXXXF14',
      state: {
        firmware_version: '3.8',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-09-17T19:17:44.3616751Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/GW0A0XXXXF14/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [   'CG0850XXX173'   ],
        updated_date: '2020-09-17T19:17:44.3633647Z'  
      } 
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'garagedoor',
      device_platform: 'myq',
      device_type: 'wifigaragedooropener',
      href: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG0850XXX173',
      name: 'Garage Door Opener',
      parent_device: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/GW0A0XXXXF14',
      parent_device_id: 'GW0A0XXXXF14',
      serial_number: 'CG0850XXX173',
      state: {
        attached_work_light_error_present: false,
        aux_relay_behavior: 'None',
        aux_relay_delay: '00:00:00',
        close: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG0850XXX173/close',
        command_channel_report_status: false,
        control_from_browser: false,
        door_ajar_interval: '00:00:00',
        door_state: 'closed',
        gdo_lock_connected: false,
        invalid_credential_window: '00:00:00',
        invalid_shutout_period: '00:00:00',
        is_unattended_close_allowed: true,
        is_unattended_open_allowed: true,
        last_status: '2020-09-17T19:43:27.951648Z',
        last_update: '2020-09-17T19:02:52.5276445Z',
        max_invalid_attempts: 0,
        online: true,
        open: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG0850XXX173/open',
        passthrough_interval: '00:00:00',
        report_ajar: false,
        report_forced: false,
        rex_fires_door: false,
        use_aux_relay: false  
      }
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'lamp',
      device_platform: 'myq',
      device_type: 'lamp',
      href: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG06A0XXX89A',
      name: 'Living Room Lamp',
      parent_device: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/GW0A0XXXXF14',
      parent_device_id: 'GW0A0XXXXF14',
      serial_number: 'CG06A0XXX89A',
      state: {
        lamp_state: 'on',
        lamp_subtype: 'unknown',
        last_status: '2020-09-17T19:17:44.3609661Z',
        last_update: '2020-07-28T17:34:59.8181461Z',
        off: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG06A0XXX89A/off',
        on: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG06A0XXX89A/on',
        online: true  
      }
    },
    {
      created_date: '0001-01-01T00:00:00',
      device_family: 'lamp',
      device_platform: 'myq',
      device_type: 'lamp',
      href: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG06A0XXX811',
      name: 'Living Room Light',
      parent_device: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/GW0A0XXXXF14',
      parent_device_id: 'GW0A0XXXXF14',
      serial_number: 'CG06A0XXX811',
      state: {
        lamp_state: 'on',
        lamp_subtype: 'unknown',
        last_status: '2020-09-17T19:17:43.9564323Z',
        last_update: '2020-07-28T17:35:03.1419227Z',
        off: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG06A0XXX811/off',
        on: 'http://api.myqdevice.com/api/v5/accounts/b9d69158-7367-XXXX-941b-48c4fef26f10/devices/CG06A0XXX811/on',
        online: true  
      }
    }
  ]
}
```

**Comment by hjdhjd** [comment]
Thanks, I have what I need here. I’m going to delete this JSON though given it contains sensitive information.

**Comment by ahnyerkeester** [comment]
Thank you for looking out for my privacy! Did I not change enough digits to Xs? Should I have changed more or all of them?

**Comment by hjdhjd** [comment]
All in a day’s work. Thank you for contributing to the community. Look forward to adding support for lights soon. Stay tuned please.

**Comment by hjdhjd** [comment]
Can you tell me what Chamberlain lights you have? Thanks.

**Comment by ahnyerkeester** [comment]
They are switches that you plug the lamp into. Model number 1901.

![IMG_0767](https://user-images.githubusercontent.com/45885366/93542047-ec716680-f90c-11ea-9092-36f6d7770fd4.jpg)

![IMG_0766](https://user-images.githubusercontent.com/45885366/93542026-e67b8580-f90c-11ea-89d9-ab9a2991cf70.jpg)

**Comment by hjdhjd** [comment]
Supported in v2.3.0 - just released. Enjoy!

**Comment by ahnyerkeester** [comment]
Works perfectly! Great job. Thank you very much.
