### ISSUE TITLE
HOOBS plugin name issues.

### ISSUE THREAD

**Issue by jlg89** [hjdhjd/homebridge-myq#117]
Just an FYI. The change from "homebridge-myq2" to "homebridge-myq" can cause odd issues in HOOBS and probably in config-ui-x (haven't verified). Manually removing the plugin and then installing the latest version should fix it.

See https://github.com/hoobs-org/HOOBS/issues/803

**Comment by hjdhjd** [comment]
It’s fine in config-ui-x. This is a HOOBS issue it seems. It’s not a plugin issue. Thanks.

**Comment by donavanbecker** [comment]
@jlg89 switch to regular homebridge and you won't have these issues, since most developers develop only for homebridge. and HOOBs is setup differently.

**Comment by jlg89** [comment]
Yes, Donavan, I know you're a "regular homebridge" (whatever that actually means) purist. But HOOBS and config-ui-x are realities, a lot of people use them because they're actually helpful and useful, and your prejudices aren't helpful.

**Comment by jlg89** [comment]
For the record, all references to homebridge-myq2 had to be removed from package.json, package-lock.json, and config.json files (in /home/hoobs/.hoobs/), and the /home/hoobs/.hoobs/node_modules/homebrige-myq2 directory had to be deleted.
