### ISSUE TITLE
Scrubbing logs by default

### ISSUE THREAD

**Issue by jarz** [hjdhjd/homebridge-myq#118]
**Is your feature request related to a problem? Please describe:**

I noticed that the logs provided by the lovely requestor on #115 include _sensitive_ information. 

In particular, the logs don't mask occurrences of these properties:
- Account IDs
- Serial Numbers
- Device IDs

**Describe the solution you'd like:**

We should protect user privacy (and any Chamberlain interventions) by masking the sensitive properties in logs by default.

I propose using a hash algorithm on those properties. It will allow for correlation between logs, but prevent the sensitive data from being exposed.

Developers gotta develop, so I assume this would be a flagged feature.

**Comment by ahnyerkeester** [comment]
Thanks for pointing this out. What did I miss?!? I changed at least 4 numbers in all of those categories to Xs to make it easy to see which thing is which but tried to obscure them enough.

**Comment by hjdhjd** [comment]
These aren’t logged or used by default, only for debugging purposes. I might deal with this in the backlog at some point, but it’s not a priority - I agree on being privacy-forward, always, but it’s debug logging for a reason.
