### ISSUE TITLE
Unable to authenticate.

### ISSUE THREAD

**Issue by jbyhb** [hjdhjd/homebridge-myq#120]
**Describe The Problem:**
Invalid myQ credentials given. Check your login and password.
Unable to authenticate. Will retry later.

MyQ app works fine. My credentials are obviously correct. Please advise.

**To Reproduce:**
Never loads correctly so no steps to reproduce.

**Logs:**

```
[9/18/2020, 11:45:57 AM] [myQ] myQ API: Invalid myQ credentials given. Check your login and password.
[9/18/2020, 11:45:57 AM] [myQ] myQ API: Unable to authenticate. Will retry later.
```

**Environment:**

* **Homebridge Version**: 1.22
* **Homebridge myQ Version**: 2.2.2
* **Operating System and OS Version**: macOS Catalina 10.15.6

**Comment by dppeak** [comment]
I'm seeing that this morning with 4.1.1 as well.

**Comment by hjdhjd** [comment]
If your credentials are correct...there’s not much to say, I’m afraid. 😄 

The response is straight from the myQ API. It doesn’t like your credentials...

@jbyhb Was it working previously?

@dppeak I have no idea what version 4.1.1 is, but it’s not this plugin. 😄

**Comment by dppeak** [comment]
sorry, posted in wrong window

**Comment by jbyhb** [comment]
Never really got this plugin to function correctly. Figured it was something on my end but I use the MyQ app all the time with no issue.

**Comment by hjdhjd** [comment]
If the myQ app works, I would carefully look at your entered credentials. It should work with the same credentials just fine. Use the Homebridge webUI, if you're not already doing so. Plugin works well for the most part.

**Comment by dppeak** [comment]
@hjdhjd The plugin is working great for me and appreciate all the work you've done to improve it.

**Comment by jbyhb** [comment]
I've changed my credentials to 'Garage1!' thinking my existing password was somehow unrecognizable to homebridge and still got the same outcome. Is there some sort of power cycle or reset you think would help?

**Comment by hjdhjd** [comment]
Nope. This is a credentials issue. You aren't entering in the email address and password you're using with myQ correctly is what it's trying to tell you. How are you configuring this plugin, exactly?

**Comment by jbyhb** [comment]
Though the HB plugin UI, not the config page. Would this matter?

**Comment by hjdhjd** [comment]
Because it seems that somehow, your credentials aren't being entered correctly. If you're correctly entering your myQ email address and password, you should be good to go. If you're not, I'm at the limit of what I can do to help I'm afraid.

Best of luck.

**Comment by jbyhb** [comment]
I updated to the latest node and npm version but no luck. Also, I changed my login info to something extremely simple, it is not being entered incorrectly. I will keep tinkering but I don't even see the door as an accessory on HB so maybe this has something to do with it?

**Comment by velazpablo** [comment]
@jbyhb I just had the same issue. Since I was using the iPhone app and it was using Face ID (maybe in your case Touch ID) to authenticate it was not using my actual credentials which after trying figured they were actually wrong.

Reset your myQ password by using the "Forgot password" and then when logged in with the temporary password reset it to what you want. And finally, update it on the Homebridge UI. 

Good luck, and let us know if you got it working.

**Comment by jbyhb** [comment]
Turned off Face ID in the myQ app it worked! Pablo you genius!

**Comment by hjdhjd** [comment]
Thanks for pitching in @velazpablo! Closing this one.
