### ISSUE TITLE
API via ipv4 only?

### ISSUE THREAD

**Issue by jeepmullet** [hjdhjd/homebridge-myq#126]
**Is your feature request related to a problem? Please describe:**
 no local IPV6 network support. Is it possible to only make API calls over IPv4 only?

**Describe the solution you'd like:**
 If Possible, have option in plugin for only IPv4 API calls

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
Thanks for reporting this, but as-written, this isn’t a plugin issue. All calls are made via HTTP, and whatever the underlying addresses get resolved via DNS get returned are what are leveraged. In a quick look, the myQ API isn’t available via IPV6 either, just IPV4.

Nothing to be done I’m afraid unless myQ chooses to support IPV6. Good luck!
