### ISSUE TITLE
HomeKit icon not reflecting current status on iOS 14

### ISSUE THREAD

**Issue by andsoitgoes** [hjdhjd/homebridge-myq#130]
**Describe The Problem:**
For the last month or so, it seems like the plug-in via homebridge is not reflecting the correct state of the garage door. Often times it will sit in an infinite circle. If I remove the plug-in and add it back, it usually works but only for a day or so. 

**To Reproduce:**
Operating the garage door via home, unfortunately it seems to be this action that triggers it. sometimes it can still work if tapped on frequently enough, but it’s always in limbo whether I can actually count on the door status. 

Even now after uninstalling and reinstalling the app, it got stuck in “opening”. I tapped it to close after it was open and home responded that it was closed, but the door was still wide open. I had to tap on the door in home again which then put it back into perpetually “opening” status. 

Nothing shows the operation of the garage door in the logs throughout this process. At all. These logs are from an earlier issue but it doesn’t seem
As though it’s connected to reporting to HomeKit. 

**Logs:**

```[9/30/2020, 2:51:58 PM] [myQ] myQ API: Successfully connected to the myQ API.
[9/30/2020, 2:51:59 PM] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: XXXXXXXX, gateway: XXXXXXXX).
[9/30/2020, 2:51:59 PM] [myQ] myQ API: Discovered device family gateway: Hub [Chamberlain Smart Garage Hub] (serial number: XXXXXXXX).
HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000041-0000-1000-8000-0026BB765291. Adding anyway.
[9/30/2020, 2:51:59 PM] [myQ] Garage Door: Door position sensor detected. Enabling battery status support.

[9/30/2020, 3:27:39 PM] [myQ] myQ API: Successfully connected to the myQ API.
[9/30/2020, 3:27:41 PM] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: XXXXXXX, gateway:  XXXXXXX).
[9/30/2020, 3:27:41 PM] [myQ] myQ API: Discovered device family gateway: Hub [Chamberlain Smart Garage Hub] (serial number: XXXXXXX).
HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000041-0000-1000-8000-0026BB765291. Adding anyway.
[9/30/2020, 3:27:41 PM] [myQ] Garage Door: Door position sensor detected. Enabling battery status support.

[9/30/2020, 7:18:51 PM] [myQ] myQ API: Connection has been reset.
[9/30/2020, 7:18:51 PM] [myQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
```

**Homebridge Configuration:**

```

Config

        {
            "email": "xxxxxx",
            "password": "xxxxxx",
            "platform": "myQ"
        }

```

**Screenshots:**

https://imgur.com/a/uNvvnp0

**Environment:**

Pi 4, docker

* **Homebridge Version**: 1.2.3
* **Homebridge-myQ Plugin Version**: 2.3.1
* **Operating System and OS Version**: raspberry pi 4 docker

**Comment by andsoitgoes** [comment]
Still having the same issue. Asking Siri to close the garage door simply doesn’t work and stalls in the opening animation. 

Nothing shows in the logs with relation to even having a connection with the myq service which is still odd

Would really love some help with this one.

**Comment by hjdhjd** [comment]
Thanks for the detailed report. A few things:

- The animation has very little to do with the action, I'm afraid. It's just chrome in the Home app, and can be buggy from time to time. Regardless - it's not really an indicator of anything.

- The logs you shared show the plugin is working correctly and as intended.

If you're seeing no response when you tap on the icon to open and close it, my suspicion is that you've uninstalled and reinstalled some version of the plugin in the past, and you may have a cached version of a zombie accessory in Homebridge.

My suggestion is to reset Homebridge and see if that works. It's an extreme measure, but it will clear out any zombie accessories you may inadvertently have.

To do that...shutdown Homebridge and delete the `~/.homebridge/accessories` and `~/.homebridge/persist` directories. Restart Homebridge, and re-pair it with HomeKit, and then test out myQ.

Best of luck.

**Comment by andsoitgoes** [comment]
The thing is that the plug-in does work, it just requires multiple presses to get it to work and it generally shows the opposite of what the status actually is. 

As for fully resetting home bridge, that’s a possibility. I’ve had a few instances where I’ve had to reload my config due to my pi running out of space, but recently I did a full reset of homebridge and added my config back. That said this seems to have been an issue through that process combined with switching from
Myq2, having to reset homebridge. The only thing I haven’t done yet is fully wipe my config. That will put me in front of a lot of work. There’s no other solution that won’t require me to start from scratch?

**Comment by hjdhjd** [comment]
In short: nope. The plugin is working correctly, as intended. The issues you seem to be having appear to be quite specific to your configuration and setup and not replicable. This plugin is in wide use by thousands, including yours truly :smile:. It’s pretty mature at this point.

Your other alternative is to stand up an entirely new homebridge instance. There’s nothing stopping you from doing it and you can do so without disturbing your original homebridge install. Google around for how to do that if you aren’t familiar. You can create a new homebridge instance with just homebridge-myq and see if that leads you down a successful path before you take on the task of rebuilding your entire install.

**Comment by hjdhjd** [comment]
I should also mention that you’re running a withdrawn version of Homebridge. 1.1.6 is the current production release. The 1.2.x series is undergoing some additional testing and troubleshooting for challenges in certain environments...we’re working on it.
