### ISSUE TITLE
MyQ Lock

### ISSUE THREAD

**Issue by robertgranholm** [hjdhjd/homebridge-myq#132]
**Is your feature request related to a problem? Please describe:**

I have a Lockitron lock and I'm looking for support for my lock so I can manage it remotely without their additional bridge and software.

I'm not a programmer, but I am an IT Director so I know my way around and would be happy to test on weekends or provide info.

**Comment by hjdhjd** [comment]
Asked and answered I’m afraid. This is unlikely to happen - all the available API endpoints are gone. Lockitron seems to be slowly, but surely, EOLed (at least from a public API perspective).

https://github.com/hjdhjd/homebridge-myq/issues/101#issuecomment-695749227

If someone can discover a public API for it, happy to add it. But it doesn’t seem to be the case...and myQ/Liftmaster is actively working to disable all access to it.
