### ISSUE TITLE
Garage Door Security via Google Home

### ISSUE THREAD

**Issue by cheitzig** [hjdhjd/homebridge-myq#133]
**Is your feature request related to a problem? Please describe:**

I have a Garage Door Opener (GDO) integrated with Homekit via the homebridge and homebridge-myq. I'm just installed homebridge-gsh, but realize there's a security hole once I have the garage doors accessible via Google Home-- a burgler could conceivably yell through even a closed window "Hey Google, open the garage door", and my garage door would open.
**Describe the solution you'd like:**

When the garage door is requested to open via Google Home, perhaps a PIN could be requested? It seems like the same issue might exist if I had an HomePod, but I don't, so I can't test.
**Describe alternatives you've considered:**

I'm happy to help think this through and even code it up. I'm not sure where the feature should be implemented though... it's not obvious whether it should be on homebridge-myq or on homebridge-gsh.
**Additional context:**

A few additional thoughts
- Homekit seems to require authentication (on the phone/ipad/etc.) before opening the door, while the Google Home does not.
- The MyQ integration that's integrated through the Google Home seems to allow closing the door, but not opening "for security reasons"

Note: I posted a similar issue on the homebridge-gsh github, because I'm not sure where / how this should / could be considered.

**Comment by hjdhjd** [comment]
Now that's a unique feature request. :smile:

@oznu should weigh in on his thoughts re: homebridge-gsh.

I don't see this as the purview of homebridge-myq. This plugin's job is to provide access to myQ accessories to HomeKit.

Google Home / Homebridge integration is @oznu 's department.

I can think of at least one workaround that you may have already thought about:

- Change garage door to something else "Hey Google, open sesame"

You can't really do multi-step interactions with HomeKit:

You: "Hey Siri, open the garage door"
Siri: "Okay, what's your PIN?"
You: "1234"
Siri: "Opening garage door"

That's just not a possible interaction I'm afraid.

I'm still trying to get my head around why anyone would want to link all the different voice ecosystems (Siri / Alexa / Google) in the first place...but that's just my curiosity talking there...

**Comment by cheitzig** [comment]
It seems like a similar integration (PIN) exists for some other GDO integrations, [here](https://support.google.com/googlenest/thread/24064763?hl=en) and [here](https://www.reddit.com/r/googlehome/comments/cp52bl/google_asking_for_a_pin/)?

Just trying to figure out how to implement something similar.

Alternatively, to "turn off" the open functionality in homebridge-gsh (i.e., I don't really need the Google Home to open the garage door, but it'd be convenient to close it at night when we forget...)

**Comment by hjdhjd** [comment]
All of that is really on the Google Home end...not myQ. 😄

**Comment by hjdhjd** [comment]
And of course the incomparable @onzu has implemented this in the latest homebridge-gsh:

https://github.com/oznu/homebridge-gsh/releases/tag/v1.8.0

Closing this one.
