### ISSUE TITLE
myQ API issue

### ISSUE THREAD

**Issue by rasterize-art** [hjdhjd/homebridge-myq#200]
**Describe The Problem:**
The API seems to be down per the Homebridge console and the garage door opening no longer works. However, via the official myQ app, opening and closing still works.

**To Reproduce:**
Uninstalled/removed configuration files from homebridge and restarted as well and still same error. Have also assigned the myQ devices static IPs (if that has any implications).

**Logs:**

```
[12/16/2020, 5:05:41 PM] [myQ] myQ API: Connection has been reset.
[12/16/2020, 5:05:41 PM] [myQ] myQ API: Unable to authenticate. Will retry later.
```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge ED67",
        "username": "XXXXXXX",
        "port": XXXX,
        "pin": "XXXX"
    },
    "accessories": [
        {
            "model": "XXXX",
            "name": "Lamp",
            "deviceUrl": "XXXX",
            "channel": 0,
            "messageId": "XXX",
            "timestamp": XXX,
            "sign": "XXX",
            "accessory": "Meross"
        },
        {
            "model": "XXX",
            "name": "XXX",
            "channel": 0,
            "messageId": "XXX",
            "timestamp": XXX,
            "sign": "XXX"",
            "accessory": "Meross"
        },
        {
            "model": "XXX",
            "name": "XXX",
            "deviceUrl": "XXX",
            "channel": 0,
            "messageId": "XXX",
            "timestamp": XXX,
            "sign": "XXX",
            "accessory": "Meross"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "platform": "config"
        },
        {
            "name": "Govee",
            "apiKey": "XXXX",
            "platform": "Govee"
        },
        {
            "email": "XXXXXXX@gmail.com",
            "password": "XXXX",
            "platform": "myQ"
        }
    ]
}
```

**Screenshots:**

<img width="643" alt="Screen Shot 2020-12-16 at 5 17 48 PM" src="https://user-images.githubusercontent.com/73791278/102413259-a8046e00-3fc2-11eb-9de2-4c17a224b791.png">

**Environment:**

* **Homebridge Version:** v1.2.4
* **Node Version:** V14.15.2
* **Homebridge-myQ Plugin Version**: v2.3.5
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** RaspberryPi 4B to host homebridge (currently typing on MacBook Pro Late 2013 running macOS BigSur 11.0.1
* **Operating System and OS Version:**  Docker 5:20.10.1~3-0~debian-buster on OpenMediaVault 5.5.18-1

**Comment by jarz** [comment]
Looks like the game of cat-and-mouse has started again... https://github.com/arraylabs/pymyq/issues/53

**Comment by rickscherer** [comment]
I'll see your pymyq, and add you a hassio.
home-assistant/core#44303

**Comment by victoras** [comment]
+1

**Comment by hjdhjd** [comment]
Off to the races. Thanks for raising it. I'll be looking closely at this later today.

**Comment by jprone** [comment]
Can confirm I am seeing the same behavior

**Comment by dppeak** [comment]
same here

**Comment by hjdhjd** [comment]
Thanks for the report - appreciate everyone is well-intentioned, but we don’t need 500 people confirming what we’ve already that we’re seeing. 😄 Feel free to follow the issue or use the emoji icon to indicate support or confirmation.

The problem isn’t going to get resolved quickly I’m afraid. IFTTT, which is a supported myQ vector, is down as well. This could all just be yet another myQ server outage...or a legitimate API change. The other major myQ-related projects are investigating as well.

Strap in.

**Comment by p2kdev** [comment]
Looks like changing user agent resolves the issue - https://github.com/arraylabs/pymyq/issues/53#issuecomment-747113258

**Comment by Marooner5** [comment]
I can confirm using this plugin that changing the user agent works here as well.

**Comment by ahnyerkeester** [comment]
@Marooner5 how'd you change it? I tried putting "pymyq" in "myQ Application Identifier Override" but it didn't fix it.

**Comment by hjdhjd** [comment]
Stay tuned. An update is coming soon.

**Comment by hjdhjd** [comment]
Fixed, hopefully for the long-term now in v2.3.6. We now generate random user agent strings at startup.

Thanks for the report.

**Comment by happyzorro** [comment]
Thank you!! works great for me now.  Really appreciate your quick response in getting this resolved.

**Comment by prkls** [comment]
Looks like myQ made some changes, on 2.3.6, but getting the following 
`[17/12/2020, 14:28:31] [Homebridge myQ] myQ API: Error: 400 Bad Request
[17/12/2020, 14:28:31] [Homebridge myQ] myQ API: Unable to authenticate. Will retry later.`

**Comment by sokulski** [comment]
Have you tried restarting Homebridge following the update? It’s performing as expected for me.

**Comment by resgroupmsr** [comment]
12/18/2020, 9:03:32 AM - [myQ] myQ API: Error: 400 Bad Request
12/18/2020, 9:03:32 AM - [myQ] myQ API: Unable to authenticate. Will retry later.

New errors today and not working again after 1 day stable with new plug in
