### ISSUE TITLE
Thousands of requests to api.myqdevices.com per day

### ISSUE THREAD

**Issue by JJJ** [hjdhjd/homebridge-myq#209]
**Describe The ~Problem~ Situation:**
Since switching away from the MyQ Home Bridge and to this Homebridge plugin, my PiHole is reporting api.myqdevices.com as the topmost permitted domain on my network. I have 2 garage door openers.

<img width="488" alt="jjj-sc-2020-12-21 at 10 27 01@2x" src="https://user-images.githubusercontent.com/88951/102798753-24a69c00-4377-11eb-90bb-9800e63194c2.png">

This represents only 24 hours of network traffic.

**To Reproduce:**
Simply install this plugin, and monitor your network DNS requests via your favorite software.

**Logs:**
No logs seem applicable, but I'm happy to provide any if it will be helpful.

**Homebridge Configuration:**

```json
        {
            "email": "<snip>",
            "password": "<snip>",
            "platform": "myQ"
        }
```

**Environment:**

* **Homebridge Version:** 1.1.7
* **Node Version:** v14.15.2
* **Homebridge-myQ Plugin Version**: v2.3.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Not relevant
* **Operating System and OS Version:** Raspbian GNU/Linux 10 (buster)

**Comment by hjdhjd** [comment]
This isn’t a bug. This is expected behavior. The plugin regularly polls the myQ API every few seconds. You can configure the intervals, as stated in the documentation.

Not sure what the issue here is. :smile:

**Comment by JJJ** [comment]
I have a hunch, but have not done any research yet to confirm it.

I suspect that the official MyQ Home Bridge device comes with hard-coded DNS settings that allow it to bypass the normal operation of my Pi-Hole. That would mean it was phoning home similarly, just unknowingly to me.

I suspect these API calls are simply part of normal operation, and not necessarily indicative of any bug or flaw in the software.

**Comment by hjdhjd** [comment]
Yep. :smile:

**Comment by JJJ** [comment]
> Not sure what the issue here is. 😄

😅 Jinx!

The plugin docs in the README.md don't mention an interval setting. I needed to poke around to find [AdvancedOptions.md](https://github.com/hjdhjd/homebridge-myq/blob/master/docs/AdvancedOptions.md), and none of those mention their controlling the polling to the external API, or what that that API is used for other than for authentication (and it seems odd to need to re-authenticate every 3 seconds).

<img width="1074" alt="jjj-sc-2020-12-21 at 11 28 33@2x" src="https://user-images.githubusercontent.com/88951/102804709-bc0fed00-437f-11eb-9b24-749a16323462.png">

So my issue, it seems, is only regarding clarity of the inner workings of the configuration keys. And, perhaps, a recommendation that something be added to the README.md to prepare new users of this plugin for this new behavior on their networks.

I am comfortable tuning the intervals to my own satisfaction, but it's somewhat unclear in the documentation what `refreshInterval` `activeRefreshInterval` and `activeRefreshDuration` do together, and what the consequences of raising them will be for the operation of my HomeKit devices.

Does that make sense?

**Comment by hjdhjd** [comment]
Documentation lives under the docs folder. I’m content with it. :smile:

The documentation seems quite clear to me, but I wrote it. If you’d like to submit a PR that improves it, terrific - happy to review and accept it, if it makes sense to do so. Otherwise, I feel this is more than adequate.

Each of those settings does exactly what is in the description for them. I’m not sure what isn’t obvious. :smile:

Alright...I’m done on this one. Suggest you try the Discord channel if you’d like to discuss this further with others. Best of luck and happy holidays!
