### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by magicman0978** [hjdhjd/homebridge-myq#219]
**Describe The Problem:**
It sometimes works to open our gate and sometimes does not. But Constantly is giving authentication errors in the logs

**To Reproduce:**
Install the my-q plugin on HOOBS and connect to myq internet gateway.

**Logs:**
This log go’s back for weeks. And I’ve removed the account id and replaced it with “....”
The problem started about 2 or 3 weeks ago. 

```

12/30/2020, 2:12:53 AM [Gate] request to https://api.myqdevice.com/api/v5.1/Accounts/..../Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
12/30/2020, 2:12:53 AM [Gate] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
12/30/2020, 2:13:06 AM [Gate] request to https://api.myqdevice.com/api/v5.1/Accounts/..../Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
12/30/2020, 2:13:06 AM [Gate] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
12/30/2020, 2:14:59 AM [Gate] request to https://api.myqdevice.com/api/v5.1/Accounts/..../Devices failed, reason: getaddrinfo EAI_AGAIN api.myqdevice.com
12/30/2020, 2:14:59 AM [Gate] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.

```

**Homebridge Configuration:**
I’m running HOOBS version 3.3.1 and Node version 12.16.3 on a pi 4
The only plugin is your myQ plugin. 

```json

"platforms": [
        {
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": ".............",
            "password": "........",
            "name": "Gate",
            "refreshInterval": 4,
            "activeRefreshInterval": 3,
            "options": []
        }
    ]

```

**Screenshots:**

**Environment:**

* **Homebridge Version:** < HOOBS version 3.3.1 >
* **Node Version:** < Node version 12.16.3 >
* **Homebridge-myQ Plugin Version**: 2.4.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**<it is triggered via the home app on about 15 different apple devices. All of which experience the instability. But the home hub is an ATV4 running tvOS 14.3 >
* **Operating System and OS Version:** < Raspbian >

**Comment by hjdhjd** [comment]
Thanks for the report! The errors you're seeing - specifically `getaddrinfo EAI_AGAIN` are DNS timeout errors on your network or with your upstream. I'd suggest taking a close look at your DNS setup and focus your troubleshooting there. Based on the logs you shared, that's the issue, not something with the plugin itself. My suggestion is to start with figuring out what might (or might not) be going on with your DNS setup.

**Comment by njsurfrider** [comment]
I am seeing this error in the hoobs log

12/31/2020, 9:24:29 AM [myQ] myQ API: Invalid myQ credentials given. Check your login and password.
12/31/2020, 9:24:29 AM [myQ] myQ API: Unable to authenticate. Will retry later.
12/31/2020, 9:24:32 AM [myQ] myQ API: Invalid myQ credentials given. Check your login and password.
12/31/2020, 9:24:32 AM [myQ] myQ API: Unable to authenticate. Will retry later.
12/31/2020, 9:24:35 AM [myQ] myQ API: Invalid myQ credentials given. Check your login and password.

just goes on and on - I check my DNS and username and password as well logged out and back in from the app - no issues. Where can I see what URL the plugin is calling? So I can test this manually?

**Comment by hjdhjd** [comment]
@njsurfrider Please don’t hijack another issue for yours. :smile: You can open a new issue, if you need to, though this question has been asked and answered several times. Please search through the closed issues for how to deal with issues relating to bad credentials. If you can’t get things going, feel free to open a new issue. The community is great at providing support, but I really want to keep issues clean for future people who come looking for answers. Thanks!
