### ISSUE TITLE
Disable push notifications when doors open/close 

### ISSUE THREAD

**Issue by pilotkid** [hjdhjd/homebridge-myq#221]
**Is your feature request related to a problem? Please describe:**
I find the push notifications when the door opens or closes to be annoying. It would be greatly appreciated if there was a setting in homebridge that can disable it for everyone in my household.

**Describe the solution you'd like:**
An option that enables a global disabling/enabling of push notifications

**Describe alternatives you've considered:**
Disabling it on a one on one basis throughout my homes devices

**Comment by hjdhjd** [comment]
Happy new year!

TL;DR: There isn’t, and there won’t be. This is controlled by HomeKit and the Home app. You can set your notification preferences for specific events within the Home app. The garage door push notification events aren’t directly generated by this (or any other) plugin. We simply inform HomeKit of state changes. HomeKit clients are responsible for notifications.

**Comment by pilotkid** [comment]
Happy new year! Poo, thank you for getting back to me so fast.
