### ISSUE TITLE
Error 400 Bad request in logs....

### ISSUE THREAD

**Issue by randymassey** [hjdhjd/homebridge-myq#230]
**Describe The Problem:**
Recursive Error 400 / retrying token entries in log.  

**To Reproduce:**
Happening under normal configuration of plugin, was previously working 100% fine with no changes made.

**Logs:**

 [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:06:43 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:06:43 PM [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:06:46 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:06:46 PM [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:06:49 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:06:49 PM [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:06:52 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:06:52 PM [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:06:55 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:06:55 PM [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:06:58 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:06:58 PM [MyQ] myQ API: Unable to update device status from myQ servers. Acquiring a new security token and retrying later.
1/8/2021, 12:07:01 PM [MyQ] myQ API: Error: 400 Bad Request
1/8/2021, 12:07:01 PM [MyQ] myQ API: Unable to update device status from myQ server

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by mbierman** [comment]
Me too. Is this just part of the "typical" problems from Chamberlain explained in the README?

**Comment by eddiem5** [comment]
Same issue, just noticed it today for the first time..    A restart does nothing to stop it...

I wonder how they change things so drastically but not break the MYQ app itself??  Different API (private)?

I do appreciate this plugin and love it's part of homekit - thanks for your efforts

**Comment by ketsugi** [comment]
Seeing the same thing here on 2.4.1

**Comment by Nastras** [comment]
Me too.

![EDA537DC-FC47-402A-B566-2BFEA383E5A8](https://user-images.githubusercontent.com/27686185/104065444-073f5200-5200-11eb-8360-86b31c225de1.jpeg)

**Comment by FishPants** [comment]
I'm seeing the same thing, door is working sporadically again.

**Comment by iap111** [comment]
Seems to be a 'cat and mouse' with Chamberlain.  See the following workaround from last time, while being looked into:
https://github.com/hjdhjd/homebridge-myq/issues/203#issuecomment-748190452

**Comment by hjdhjd** [comment]
It’s like nobody looks at the open issues...locking and closing this one. Please refer to issue  #226 

:smile:
