### ISSUE TITLE
Lockitron bolts lock support

### ISSUE THREAD

**Issue by pponce** [hjdhjd/homebridge-myq#248]
**Is your feature request related to a problem? Please describe:**
no

**Describe the solution you'd like:**
Lockitron bolt lock support

**Describe alternatives you've considered:**
none

**Additional context:**
I see that with version 2.5 there might be able to be lock support finally! I own 2 lockitron bolts and if there are commands i can run that would help get the information you need to support locks i can try and help out. Let me know how i can help.

**Comment by hjdhjd** [comment]
I really appreciate the enthusiasm, but I want to set expectations.

Right now, the priority is:

* Making sure everything works to provide the basics that everyone expects - opening garage doors.
* Then it's making sure things like lamps and the existing features of this plugin work.
* Then it's looking at how to expand support to other things, like locks and cameras.

There is no timeline, nor will I speculate on one. This is a labor of love done in people's free time, when we can. I'm just glad we're up and running on the new API...now the next stage of exploration begins.

When we get there, I'll reopen this request. We are **not** anywhere near that point.

**Comment by whreams** [comment]
Spot on.  Appreciate your patience to the masses.

**Comment by pponce** [comment]
All good.  expectations set. 
I’m just happy there might be a chance here....
