### ISSUE TITLE
Garage door openers in perpetual opening / closing state in HomeKit -- 403 Forbidden errors

### ISSUE THREAD

**Issue by bldnightowl** [hjdhjd/homebridge-myq#261]
**Describe The Problem:**

When using HomeKit to interact with a garage door device added through the HomeBridge myQ plugin, the device stays in the perpetual "Opening..." state in the HomeKit app. When the garage door eventually decides to close on its own or HomeKit is used, the perpetual state "Closing..." is shown.

**To Reproduce:**

Use HomeKit to open a garage door that is configured through the HomeBridge myQ plugin.

**Logs:**

```
[Garage Door Hub] myQ API: https://account-devices-gdo.myq-cloud.com/api/v5.2/Accounts/.../door_openers/.../open Error: 403 Forbidden
[Garage Door Hub] myQ API: Unable to send the command to myQ servers. Acquiring a new access token.
[Garage Door Hub] myQ API: Successfully connected to the myQ API.
```
Testing the link referenced in the log message directly in a browser yields:
```
{"Error":{"Code":"UnsupportedApiVersion","Message":"The requested resource with API version '5.2' does not support HTTP method 'GET'."}}
```

**Homebridge Configuration:**

```json
        {
            "email": "...",
            "password": "...",
            "name": "Garage Door Hub",
            "platform": "myQ"
        }
```

**Screenshots:**

**Environment:**

* **Homebridge Version:**  1.2.5
* **Node Version:**  v14.15.1
* **Homebridge-myQ Plugin Version**: 2.6.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14.4 and macOS Big Sur 11.2
* **Operating System and OS Version:**  Docker

**Comment by hjdhjd** [comment]
Thanks for the report. Testing the link isn’t really meaningful and **highly** ill advised. It’s not meant for human consumption, and will only serve to potentially flag your myQ account, given the unsupported nature of all this.

You’re also running a beta version of Homebridge. I would encourage you to only run production versions of Homebridge - the current production release is 1.1.17. I doubt it’s the direct cause, but beta versions of Homebridge are unsupported. Only production releases are supported here.

Finally, you’ve posted a brief log extract - I’d appreciate it if you can post **all** myQ-related log messages.

Off the bat, nothing looks particularly out of place. What’s your myQ-related hardware setup, and what OS are you running Homebridge on?

**Comment by bldnightowl** [comment]
I simply took the latest release of Homebridge from here:
https://github.com/homebridge/homebridge/releases

I had no idea 1.2.5 was considered a beta release. Only now do I notice that 1.1.7 (is that what you meant instead of 1.1.17?) is the last tagged as 'Verified.' Is this why you say it's the last production version?

I am running Homebridge under the Alpine-Linux Docker image deployed on a Synology NAS.

I did post all myQ related log messages as far as I could tell.

**Comment by arrmo** [comment]
Hi,

FYI, I was going to raise a similar issue, but just hadn't gotten to it yet. HomeKit is "stuck" in the state as noted above, but the myQ app seems to have it right - most of the time. I say that because I sometimes get into a "Sensor Error" state in myQ (when this "stuck" state is happening). @bldnightowl, do you also see this Sensor Error in myQ?

Oh, and I'm running v1.1.7, on Ubuntu Linux.

Thanks!

**Comment by bldnightowl** [comment]
But that all said, I think I have discovered the root cause of the problem. I am blocking outbound internet traffic from the myQ HomeKit Bridge. I really don't like devices that phone home and want to be able to control all my devices locally -- with the only external interface through Apple's HomePod acting as HomeKit gateway. This worked fine when I added the myQ HomeKit Bridge directly to HomeKit -- well mostly fine, every once in awhile I'd have to repeat commands to get the garage door to function. But otherwise, everything behaved normally and as expected. It's the intermittent bad behavior I hope to eliminate with your Homebridge myQ plugin.

I opened up the firewall to allow the myQ HomeKit Bridge your plugin is interacting with to access the Internet again -- and things started behaving.

So I guess I understand now that your plugin is strictly passing commands through the Internet to trigger myQ's servers to send commands back to their HomeKit bridge to do the actual work?

**Comment by hjdhjd** [comment]
Nope. :smile: There are more. Please look through your logs.

You also haven’t answered the question about your myQ-related hardware.

Additionally, is this an error that is happening constantly, or occasionally?

**Comment by bldnightowl** [comment]
@hjdhjd myQ-related hardware: myQ HomeKit Bridge + two Liftmaster garage door openers paired with it.

**Comment by bldnightowl** [comment]
@hjdhjd These errors happen every single time.

**Comment by hjdhjd** [comment]
Awesome! Well, there you have it...you can’t block access for the hardware bridge. It is ultimately what controls your myQ device. Any attempt to send a command will fail, as a result. :smile:

**Comment by bldnightowl** [comment]
@hjdhjd Then why does this setup mostly work when the myQ Bridge is directly added to HomeKit?

**Comment by bldnightowl** [comment]
And @arrmo - no, I never saw any SensorErrors.

**Comment by hjdhjd** [comment]
> @hjdhjd Then why does this setup mostly work when the myQ Bridge is directly added to HomeKit? To be clear, I was presuming / hoping your plugin would be translating HomeKit API calls to whatever native protocol the myQ devices use without having to go to the Internet.

This plugin works by speaking to the myQ API. The hardware bridge is required to speak to the myQ API. This plugin does not locally speak to anything, nor is it designed to do so.

If you want to firewall off the hardware bridge, you’re out of luck. :smile:

**Comment by arrmo** [comment]
FYI, no firewall here - but that's OK, seems this particular issue is resolved. Will keep trying to debug what I'm seeing (for now at least 😆).

Thanks!

**Comment by bldnightowl** [comment]
Sort of unfortunate that Internet access is required to control a local device -- hate it when device manufacturers do that, it's just stupid and a total violation of the way HomeKit is supposed to work. But I agree this is not the fault of your plugin.

**Comment by hjdhjd** [comment]
It’s not a violation of how HomeKit is supposed to work. People often misunderstand or misquote the spec. Bridged devices, like these, are not required to have local access, only to be able to locally accept HomeKit commands, which it does.

**Comment by arrmo** [comment]
Snapshots from my phone - showing the issue I'm seeing. Open a different ticket for this? Thanks!
![IMG_0840](https://user-images.githubusercontent.com/8756384/107173624-d9c7fe80-698d-11eb-8353-9962b3389bad.PNG)
![IMG_0841](https://user-images.githubusercontent.com/8756384/107173627-dcc2ef00-698d-11eb-86ac-cd4dd05d0398.PNG)

**Comment by hjdhjd** [comment]
@arrmo Please don't hijack one issue for another. This issue is closed. Thanks.

**Comment by arrmo** [comment]
Sorry! Definitely wasn't my intention - was just not sure how to handle the issue I am having, as it's very similar to what is noted above. But I'll try to debug here for now, get a clearer picture of it - then open a new ticket if needed.

Again, my apologies.

**Comment by hjdhjd** [comment]
No worries. Don’t confuse similar symptoms with causality. :smile:

**Comment by arrmo** [comment]
LOL - well said 🤣. Thanks!
