### ISSUE TITLE
Control locally (no MyQ cloud)

### ISSUE THREAD

**Issue by sCrunch021** [hjdhjd/homebridge-myq#265]
**Is your feature request related to a problem? Please describe:**
I don’t trust cloud services and block all my smart home devices from connecting to the Internet via my firewall. This is why I love HomeKit. This plugin does not work when the garage door is blocked in my firewall. This plugin is far more reliable than the $50 Insignia native HomeKit opener so I’d love to use this plugin instead.

**Describe the solution you'd like:**
If it is possible to talk to the MyQ directly like how my phone does it in the app that would be ideal.

**Describe alternatives you've considered:**

Insignia 

**Additional context:**

N/A

**Comment by hjdhjd** [comment]
This is simply not possible, and may never be possible. You’re going to have to live with cloud control of myQ...that’s how myQ works. Local control is unavailable to the best of the community’s knowledge. If it ever is, sure...we’d all like that. But don’t hold your breath. 😄 

Thanks for the suggestion!
