### ISSUE TITLE
can't retrieve manufacturer and model information

### ISSUE THREAD

**Issue by xraynano** [hjdhjd/homebridge-myq#300]
**Describe The Problem:**

Errors reported in log about retrieving Manufacturer and Model information. Otherwise, operation seems okay.
**To Reproduce:**

Restart Hoobs, happens each time.
**Logs:**

```
3/3/2021, 9:32:57 AM [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG08009AC18B, gateway: GW33000AF1C1).
3/3/2021, 9:32:57 AM [myQ] myQ API: Discovered device family gateway: Hub (serial number: GW33000AF1C1).
3/3/2021, 9:32:57 AM [myQ] Garage Door: Adding garagedoor device to HomeKit: Garage Door (serial number: CG08009AC18B, gateway: GW33000AF1C1).
3/3/2021, 9:32:59 AM [HOOBS RPi 91L 1449@Garage Door@@Manufacturer] characteristic value expected string and received undefined
3/3/2021, 9:32:59 AM [HOOBS RPi 91L 1449@Garage Door@@Model] characteristic value expected string and received undefined
3/3/2021, 9:32:59 AM [myQ] Garage Door: Closed.```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:**  3.3.3
* **Node Version:**  14.15.1
* **Homebridge-myQ Plugin Version**: 2.6.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** IPhone XS, current iOS
* **Operating System and OS Version:** 
5.10.11+

**Comment by hjdhjd** [comment]
Thanks - it’s already been reported. This is a cosmetic issue that will be resolved in the future, and not a functional error. Closing the duplicate.
