### ISSUE TITLE
Please improve documentation on Installation for standalone use

### ISSUE THREAD

**Issue by flavio-fernandes** [hjdhjd/homebridge-myq#318]
**Is your feature request related to a problem? Please describe:**
The install part of the documentation is not very friendly for a Nodejs newbie
who wants to use this project standalone (not using Homebridge).

I could not make it work. I got as far as installing node and run the command
sudo npm install -g homebridge-myq

But after that point, there was not enough info on how to start the code,
and where the json configuration file mentioned could be tweaked.

**Describe the solution you'd like:**
Please add a few more lines in the [install section](https://github.com/hjdhjd/homebridge-myq#installation) on how one can run 
homebridge-myq straight out of the shell terminal. If this is common
sense for a Node developer (unlike me), some pointers in the documentation
may be enough.

**Describe alternatives you've considered:**
I ended up writing an mqtt front end for https://github.com/arraylabs/pymyq
(shameless plug):  https://github.com/flavio-fernandes/mqtt2garage
I wish I could have used this repo instead, because it offers exactly what I was
looking for.

**Additional context:**
I find Home Assistant and homebridge great projects, but I rather use lower level
libraries such as this for better understanding and control of my home devices. Thank
you so much for the creation and the maintenance of this project.

**Comment by hjdhjd** [comment]
Thanks for the suggestion, however this plugin is not intended to be used standalone.
