### ISSUE TITLE
Option to disable battery status

### ISSUE THREAD

**Issue by mleiphamellis** [hjdhjd/homebridge-myq#332]
**Is your feature request related to a problem? Please describe:**
My garage door sensor erroneously reports low battery in the MyQ app which is picked up by this plugin and relayed to the accessory status in Homebridge.

**Describe the solution you'd like:**
I would appreciate a feature option to disable battery status from passing through to Homebridge.

**Describe alternatives you've considered:**
Replacing the battery 😀

**Additional context:**
In my case the low battery status has been present for well over a year and persists with new replacement batteries. At one point I measured the battery voltage, found it to be in spec, and am still running on it a year later. No issues whatsoever otherwise!

If the voltage detection in the hardware is crude the symptoms mine exhibits may not be isolated and this feature could benefit other happy users of the plugin!

**Comment by hjdhjd** [comment]
It’s coming. Stay tuned. Thanks for the request!

**Comment by mleiphamellis** [comment]
Hello! Might this feature still be configurable in the future?
