### ISSUE TITLE
Status Updates (HomeKit)

### ISSUE THREAD

**Issue by arrmo** [hjdhjd/homebridge-myq#334]
**Describe The Problem:**

Hi,

My apologies if this one seems vague initially! Not my intention, but also not quite sure yet what to capture for logs - I will, no issue at all, but need some guidance on what would help out here. Thanks!

The issue I am seeing is that very often when I use HomeKit to open / close my (myQ) garage door opener ... the state changes to opening or closing, with a spinning circle. And it stays there. Never progresses to open or closed. Raising it now, as I'm seeing it on a second device as well (my wife's cell phone also, was thinking before it was just my phone). What's also odd ... if I come back to the spinning circle, for example the next morning (i.e. 8 hours later) ... and tap on it => then the state changes correctly (and very quickly / almost immediately). But not until then. And at that point I get the HomeKit notification (e.g. door closed), even though it was complete 8 hours ago.

Am I making sense? Hopefully 🤣. Please do let me know what logs would help!

**To Reproduce:**

Outlined as above - just use HomeKit to open or close the device ... and the spinning starts.

**Logs:**

OK, this is very odd - garage door was opened and closed today, not showing in the logs. Perhaps that's part of the issue? And, I opened HomeKit, still spinning (screenshot below) ... tapped it, changed to the correct state - but not showing in the log! It was at 5:50 pm (17:50), Apr 08/21
```
$ grep -i myQ /var/lib/homebridge/homebridge.log
[4/7/2021, 4:43:33 PM] [myQ] Garage Door, Double: Open.
[4/7/2021, 7:23:06 PM] [myQ] Garage Door, Double: Closed.
[4/7/2021, 7:27:03 PM] [myQ] myQ API: Connection has been reset.
[4/7/2021, 7:27:03 PM] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[4/7/2021, 7:27:08 PM] [myQ] myQ API: Successfully connected to the myQ API.
[4/8/2021, 6:10:32 AM] [myQ] myQ API: Connection has been reset.
[4/8/2021, 6:10:32 AM] [myQ] myQ API: Unable to update device status from the myQ API. Acquiring a new access token and retrying later.
[4/8/2021, 6:10:37 AM] [myQ] myQ API: Successfully connected to the myQ API.
[4/8/2021, 10:40:45 AM] [myQ] myQ API: Connection has been reset.
[4/8/2021, 10:40:45 AM] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[4/8/2021, 10:40:49 AM] [myQ] myQ API: Successfully connected to the myQ API.
```

**Homebridge Configuration:**

```json
Not sure anything is relevant here, as the device is present?
```

**Screenshots:**

![IMG_0894](https://user-images.githubusercontent.com/8756384/114109816-a7f2eb80-989b-11eb-9f07-ce702443e9b5.PNG)

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:** v14.16.0
* **Homebridge-myQ Plugin Version**: homebridge-myq v2.6.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** v14.5
* **Operating System and OS Version:** Ubuntu 20.10

**Comment by hjdhjd** [comment]
Thanks for the report. I understand the frustration, and HomeKit can be finicky. Unless you have a genuinely reproducible use case that I can replicate myself, I’m afraid there’s not much to do here.

That said, first and foremost: you are running beta iOS versions. **Any beta versions of iOS are explicitly unsupported. You are on your own I’m afraid.** There are often bugs and issues like the above. If you can reproduce the above on production iOS versions, with a clear path to recreate it - happy to look further into it.

Best of luck!

**Comment by hjdhjd** [comment]
If one device is on a beta iOS version, it makes the entire install suspect I’m afraid. Best of luck!

Closing this one. The logs don’t say anything other than things are working as they should I’m afraid.

**Comment by arrmo** [comment]
> If one device is on a beta iOS version, it makes the entire install suspect I’m afraid. Best of luck!

NP! Wasn't aware of that, appreciate the info. Will (soon) get back off the beta, see if it resolves then.

Thanks!

**Comment by arrmo** [comment]
Hi,

OK, all devices off beta - issue still exists. And I was doing some checking / debugging, as there are a few different "links" here to consider, meaning,
1) myQ to HomeBridge (this code / utility)
2) HomeBridge to HomeKit

It seems that the issue is in 1), saying that because HomeBridge is not showing the correct state (vs. my eyeballs, checking out the actual door ... LOL!). I do notice that when it fails,
a) Press the GD control in HomeKit, it starts spinning, and saying "Opening" (or Closing)
b) If the myQ to HomeBridge link works, then all proceeds and work fine, but,
b2) If it doesn't ... HomeBridge is in the wrong state (i.e. never changes like it should), and HomeKit stays spinning forever.
c) If "stuck" (spinning) ... a quick tap in HomeKit forces the button to get the current HomeBridge state => it updates, and stops spinning. But it's in the wrong state (vs. eyeballs :-)).

Make sense? Any logs that would help out?

Thanks!
