### ISSUE TITLE
Request to https://accounts.myq-cloud.com/api/v6.0/accounts failed, reason: connect ETIMEDOUT

### ISSUE THREAD

**Issue by themick4u** [hjdhjd/homebridge-myq#343]
**Describe The Problem:**
 I am repeatedly seeing this in my logs: request to https://accounts.myq-cloud.com/api/v6.0/accounts failed, reason: connect ETIMEDOUT

**To Reproduce:**

**Logs:**

**Environment:**

* **Homebridge Version:**  HOOBS
* **Node Version:**  14.16.1
* **Homebridge-myQ Plugin Version**:  2.6.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** ios 14.4.2
* **Operating System and OS Version:**  Raspian Buster

**Comment by hjdhjd** [comment]
This looks like a network error. I wouldn’t worry about it. If you have a persistent, long-term issue, feel free to open a new report.

Best of luck!

**Comment by themick4u** [comment]
Ok great! Thanks
