### ISSUE TITLE
Is it possible to add a feature to control HomeKit enumeration order for CarPlay?

### ISSUE THREAD

**Issue by ozpaulb** [hjdhjd/homebridge-myq#344]
**Is your feature request related to a problem? Please describe:**

This is a feature request - not a bug/real issue.

Hi - I’ve got two Chamberlain B550 garage door openers in the same home (two garage doors).  Everything works great with homebridge-myq.

But, when I return home in my car, CarPlay (possibly related to Siri suggestion) will show a button on my car’s screen to open a garage door.  It’s very handy, but always shows the wrong garage door (I always use the other one).

Googling has told me that this is an issue with CarPlay, and (it seems) that the most recently added garage door is the one presented.  I think that’s just a guess (a reasonable one).  I suppose it could be based on the name of the device (alpha sort) or the serial number/UUID order.

It would be nice to be able to configure homebridge-myq in a way that could overcome this issue.

**Describe the solution you'd like:**

Depending on the real source of the problem, I can think of a couple of solutions:

- option to control HomeKit enumeration order of myQ garage doors (perhaps a string of serial numbers in the desired enumeration order).  homebridge-myq could enumerate all of the myQ devices, sort by the specified enumeration order, then add them to HomeKit in that order.  Perhaps with a delay between adding devices (in case ‘time of add’ is somehow related to the CarPlay choice).

- if serial number and/or UUID are responsible for CarPlay garage choice, then maybe a way to specify an alias for a serial number or UUID (are serial numbers presented to HomeKit, or just the UUID?).  so, if I know the real UUID that homebridge-myq generates for “garage door a”, I could have an option “UUID_alias=old.UUID,new.UUID”.

**Describe alternatives you've considered:**

I’ve experimented a bit with renaming the garage doors, and adding them to myQ in a different order, but it doesn’t seem to be helping.  One issue is that I’m only presented with the garage door button in my car when I leave my house/come back, which makes experimentation more difficult.  Also, Google says that “Siri suggestions” is involved, so maybe Siri has some memory of the “correct” door that it’s been choosing, and maybe it’s difficult to override that.

**Additional context:**

This obviously isn’t really an “issue” with homebridge-myq - just something that may make it a bit more useful in the CarPlay scenario.  Of course, it’s possible that Apple will add an option to choose the preferred garage door at some point in the future, making such changes unnecessary.

**Comment by iRayanKhan** [comment]
I had this issue, and fixed it by splitting my garages in child bridges. I had to factory reset my dash with CarPlay, add the first bridge, use the CarPlay controller, then add the second one.

**Comment by hjdhjd** [comment]
Thanks @iRayanKhan! Would you mind providing some instructions for folks to follow who find this request in the future?

**Comment by iRayanKhan** [comment]
> Thanks @iRayanKhan! Would you mind providing some instructions for folks to follow who find this request in the future?

Will do

**Comment by ozpaulb** [comment]
I’m definitely curious about how the problem is solved by splitting things into child bridges.

if “enumeration order” is an issue (which I believe it to be, but could be wrong), then wouldn’t “enumeration order of child bridges” also be an issue?  how do you make the enumeration order of child bridges a constant?

I’m assuming you’re adding “garage door 1” to “child bridge 1” and “garage door 2” to “child bridge 2”, but how does this ensure that “garage door X” (1 or 2, depending on what I want) will be the one that CarPlay chooses as the “default” garage door?

Thanks in advance for any details on your ideas!

**Comment by iRayanKhan** [comment]
I'll explain in the write up, but CarPlay will default to whatever garage door was added first. I did a few hours of testing, and came to the result that splitting them into two, adding the first, using the garage, then adding the second, kept it on the first garage. 

You could re-enable the disabled garage in the config once you pair the first garage.

**Comment by ozpaulb** [comment]
Hi -

Thanks for the info you’ve provided so far.

Today I made a child bridge and added a “Disable” for the serial number of the garage door that I do NOT want as my CarPlay default (so the only Enabled door is the primary door I want to use from CarPlay).

When I got into my car, it was still suggesting the old (incorrect) door, saying that it was not responding (since I had Disable set I guess).

So, as you suggested, it’s important to tell CarPlay to “forget” your car and then re-enable it - at that point it suggested the correct door opener.

I’m wondering what I should do next. I could just get rid of the “Disable” for the “other” garage door, and hope that it doesn’t appear as the default suggested door in CarPlay.

Or, I could add a second child bridge (which is what I think you were suggesting), and on that bridge I should “Disable” the primary door (and leave the alternate door enabled).

Do you think the second child bridge is required, or can I just remove the “Disable” for my second door (and CarPlay will continue to use my primary door, as it is right now)?

Thanks again for your help!

On Apr 30, 2021, at 22:48, Rayan Khan ***@***.***> wrote:

﻿

I'll explain in the write up, but CarPlay will default to whatever garage door was added first. I did a few hours of testing, and came to the result that splitting them into two, adding the first, using the garage, then adding the second, kept it on the first garage.

You could re-enable the disabled garage in the config once you pair the first garage.

**Comment by iRayanKhan** [comment]
You should be able to remove the disable part for the secondary garage. I just have 2 bridges still, since it works.
