### ISSUE TITLE
Can we hook onto the Liftmaster Elite 8500W Remote Light?

### ISSUE THREAD

**Issue by SemoTech** [hjdhjd/homebridge-myq#363]
**Is your feature request related to a problem? Please describe:**
Not a technical issue, just questions about functionality or new features

**Describe the solution you'd like:**
Just installed a new Liftmaster Elite 8500W and it works great in HomeKit thought the homebridge-myq plugin, thanks @hjdhjd for all the hard work!  

The Liftmaster unit also comes with the "MYQ® REMOTE LED LIGHT" Part # 827LM.  Without that light paired and plugged into power, there are some limitations to overall functionality, as the door will not close from the MyQ App or from HomeKit! It wants the light connected so it can flash it, and beep loudly several times, before and during the door closing process. 

The 1st question I have is there any way to simulate the light (trick the opener) without actually having it paired and plugged in?

The 2nd question is if simulating the light is not possible, can we get a trigger that the light has turned on - exposed in HomeKit by the homebridge-myq plugin - so that I can create a separate automation, and also turn on the main garage ceiling lights, through a WiFi smart switch?

Thank you.

**Describe alternatives you've considered:**
None I am aware of. 

**Additional context:**
n/a

**Comment by jarz** [comment]
@SemoTech If the light appears as a separate accessory in the myQ app, it _should_ be able to be controlled by the plugin.

I doubt it's possible to 'trick' the opener as it appears to use a separate wireless connection between the opener and the light (just like the opener and a remote in a vehicle).

From the product page...
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/90255/118408335-2c7f1980-b653-11eb-91a5-d58fd29ca3ae.png">

**Comment by hjdhjd** [comment]
@jarz is correct. The rule of thumb is: if it’s accessible in the native myQ app, it can be made accessible in this plugin.

**Comment by SemoTech** [comment]
Thanks for the prompt replies @jarz and @hjdhjd.  Sadly the light does not appear as an accessory in the MyQ app, even tho it is required by the opener to function properly.  This is disappointing as it does seem to mean we cannot check on its state and create triggers.

FYI, opening the garage door by any method does not require the light to be plugged in and connected, however closing it from the MyQ App or via Homebridge does!   Interestingly you can close the door from the button, or the car using HomeLink, even with the light unplugged and not connected.  I assume the light is needed for all "remote" operations while local control allows it to be disconnected. So maybe there is a way to bypass it....

**Comment by schwaggy** [comment]
The light is required for remote operation (along with the stupid beeping) to warn others who might be in the area of the closing door. It is assumed that when you use the wall control or the car clicker, you have a visual on the door and there's less chance of somebody getting hurt. It sure would be nice to have an option to not have these warnings when closing remotely.

**Comment by hjdhjd** [comment]
Your beef is with Liftmaster/Chamberlain. This plugin can't do more than what the myQ app already does I'm afraid. :smile:

**Comment by SemoTech** [comment]
Yeah, @schwaggy sounds exactly correct.  Makes me want to do a mod, open up their stupid light and cut the trace to the speaker and the LED...  It should still "work"...  
I hear ya @hjdhjd, sadly do not think we can trigger automation based on the built-in motion sensor of the door opener or feedback from the stupid LED light...
