### ISSUE TITLE
MYQ Connect has been reset 

### ISSUE THREAD

**Issue by Tesla-P100FX** [hjdhjd/homebridge-myq#390]
**Describe The Problem:**
While the service work the Homebridge log constantly shows error that the connection has been reset 

**To Reproduce:**
happens by itself now need to take any action 
**Logs:**

[myQ] myQ API: Connection has been reset.
6/6/2021, 8:21:02 PM [myQ] myQ API: Unable to retrieve account information. Will retry later.
6/6/2021, 8:21:07 PM [myQ] myQ API: Successfully connected to the myQ API.
6/6/2021, 9:20:36 PM [myQ] myQ API: Connection has been reset.
6/6/2021, 9:20:36 PM [myQ] myQ API: Unable to retrieve account information. Will retry later.
6/6/2021, 9:20:41 PM [myQ] myQ API: Successfully connected to the myQ API.
6/7/2021, 1:48:11 AM [myQ] myQ API: Connection has been reset.
6/7/2021, 1:48:11 AM [myQ] myQ API: Unable to retrieve account information. Will retry later.
6/7/2021, 1:48:16 AM [myQ] myQ API: Successfully connected to the myQ API.
6/7/2021, 2:00:03 AM [Wemo] [Rear Deck Exterior Light] current state [off].
6/7/2021, 3:37:18 AM [myQ] myQ API: Connection has been reset.
6/7/2021, 3:37:18 AM [myQ] myQ API: Unable to retrieve account information. Will retry later.
6/7/2021, 3:37:23 AM [myQ] myQ API: Successfully connected to the myQ API.
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**
{
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": "",
            "password": "",
            "options": []
        }

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Homebridge Version:** Hoobs 3.3.5 
* **Node Version:**  14.15.1



* **Homebridge-myQ Plugin Version**:   2.6.2 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**<!-- Type of Apple device you're using and associated OS version -->
* **Operating System and OS Version:** <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker -->

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by hjdhjd** [comment]
This is normal and expected behavior. Please see other closed issues on this.
