### ISSUE TITLE
Controlling the Light State

### ISSUE THREAD

**Issue by alexcooperdev** [hjdhjd/homebridge-myq#452]
**Is your feature request related to a problem? Please describe:**

> No it's not.

**Describe the solution you'd like:**

> I would like to be able to control the built-in LED light and I did not see anything in the docs regarding a light. It would be great to create an additional switch accessory for this.

**Describe alternatives you've considered:**

> I looked at the [myq-api](https://www.npmjs.com/package/myq-api#) library, [which appears to support setting the light's state](https://www.npmjs.com/package/myq-api#setlightstateserialnumber-action), but it seems to be outdated and no longer working with the newest version of the MyQ API.

**Additional context:**

> My garage door opener is a Chamberlain B1381, but since all MyQ openers have lights, I doubt that's super relevant.

**Comment by hjdhjd** [comment]
Support for lights already exists in the plugin. If you can individually control the lights through the native myQ app, you can control them in this plugin. 

If you cannot then they are not exposed to myQ in the first place and can't be made accessible.

Both types of lights exist in the Liftmaster / Chamberlain ecosystem.

**Comment by alexcooperdev** [comment]
Hmm. Is it something I need to add in my plugin's Feature Options section? Or is it something that would be enabled and added automatically? Sorry for all the questions, I'm just not seeing anything about it in the docs. Could you point me in the right direction?
