### ISSUE TITLE
[homebridge-myq] This plugin generated a warning from the characteristic 'Model'

### ISSUE THREAD

**Issue by petertuton** [hjdhjd/homebridge-myq#478]
**Describe The Problem:**
Although not a functional issue, the log file is filled with warning messages about the characteristic 'Model', as per the log snapshot. This makes it challenging to diagnose other issues, e.g., with other plug-ins, due to unwarranted noise in the log. 

**To Reproduce:**
Configure required settings, leaving optional settings as default, i.e., empty. 

**Logs:**
Snapshot from log:
```
[homebridge-myq] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
```

**Homebridge Configuration:**
```json
        {
            "email": "<removed>",
            "password": "<removed>",
            "platform": "myQ"
        }
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v14.16.1
* **Homebridge-myQ Plugin Version**: v2.6.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** HomePod v14.7
* **Operating System and OS Version:** Raspbian GNU/Linux 10 (buster)

**Comment by petertuton** [comment]
FWIW, I see there are other closed issues either acknowledging this issue or they've been auto-closed for not following the template (#294 #300 #349). I recommend leaving this issue open until it's fixed so that people who are experiencing the issue see that it's already logged and don't create yet another issue.

Thanks for the great plug-in, btw!

**Comment by hjdhjd** [comment]
Thanks, appreciate (yet another :smile:) report on this. It’s cosmetic…I will resolve it in a future update at some point. It is not a priority, however. Thanks for the report!

**Comment by hjdhjd** [comment]
Should be fixed in v2.6.5. Happy now? :smile:

**Comment by petertuton** [comment]
Legend! Thanks. VERY happy now 😁

**Comment by hjdhjd** [comment]
Now go pay it forward!
