### ISSUE TITLE
Intermittently fails to report the correct status of my garage door.

### ISSUE THREAD

**Issue by marcelgood** [hjdhjd/homebridge-myq#487]
**Describe The Problem:**
Ok, trying again. Not sure how to say this any different, but the plugin intermittently is not reporting the correct state of the garage door. This morning my garage door was open, but the Home app said it was closed. It's a if the plugin didn't detect that the garage door had been opened. There's nothing in the log about the event. 

**To Reproduce:**
I don't have steps to reproduce it. It happens intermittently. 

**Logs:**
Nothing in the log. Following are the log entries around the event. At around 10:44 I manually opened the garage door, but the myQ plugin has no record of that event. However, about 1.5 hours later when I came home it correctly reports that the garage door was opened. 

```
[25/08/2021, 09:48:49] [Ring] Reconnecting location socket.io connection
[25/08/2021, 09:48:50] [Ring] Creating location socket.io connection - My Home
[25/08/2021, 09:48:50] [Ring] Ring connected to socket.io server
[25/08/2021, 10:45:09] [Ring] Arming (Home) Alarm
[25/08/2021, 12:21:47] [Ring] Disarming Alarm
[25/08/2021, 12:22:01] [myQ] Garage: Open.
[25/08/2021, 12:22:55] [myQ] Garage: Closed.
```

**Homebridge Configuration:**

```json
        {
            "email": "[My Email]",
            "password": "[My Password]",
            "platform": "myQ"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v14.17.4
* **Homebridge-myQ Plugin Version**: v2.6.5
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14.7.1
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)

**Comment by jlg89** [comment]
What messages do you see if you enable debug logging?

```
 {
            "email": "[My Email]",
            "password": "[My Password]",
            "platform": "myQ",
            "debug": true
        },
```

**Comment by marcelgood** [comment]
This is what I'm currently getting. I noticed that it was reporting a weak WiFi signal, even though one of my mesh WiFi points is in the garage, but it seemed to connect to one of my other points farther away. I temporarily moved the hub to make it less likely to get a signal from any of the other points and it now reports an excellent WiFi connection. However, I haven't noticed any connection problems with the myQ app and my Ring alarm system. Both have been reporting the correct status, and the myQ app so far has never failed to open and close the garage door, except yesterday due to myQ's known service disruption. 

I'll keep an eye on the log. This morning, the plugin ignored a close command and I had to use the myQ app to close the garage door. 

```
[28/08/2021, 12:50:17] [myQ] {
  count: 2,
  items: [
    {
      account_id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      created_date: '0001-01-01T00:00:00',
      device_family: 'garagedoor',
      device_model: 'virtualgaragedooropener',
      device_platform: 'myq',
      device_type: 'virtualgaragedooropener',
      href: '/accounts/d3c92ef4-4295-4e3c-84bf-c401e42105c4/devices/garagedoor/CG084690FD17',
      name: 'Garage',
      parent_device_id: 'GW330027D1E9',
      serial_number: 'CG084690FD17',
      state: {
        absolute_cycle_count: 0,
        attached_camera_serial_number: '',
        door_state: 'closed',
        dps_battery_critical: false,
        dps_low_battery_mode: false,
        dps_no_communication: false,
        is_scheduling_allowed: true,
        is_unattended_close_allowed: true,
        is_unattended_open_allowed: true,
        last_status: '2021-08-28T19:49:26.4320505Z',
        last_update: '2021-08-28T17:45:57.4829711Z',
        monitor_only_mode: false,
        number_of_learned_dps_devices: 1,
        online: true,
        sensor_comm_error: false,
        service_cycle_count: 0
      }
    },
    {
      account_id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      created_date: '0001-01-01T00:00:00',
      device_family: 'gateway',
      device_model: 'hub',
      device_platform: 'myq',
      device_type: 'hub',
      href: '/accounts/d3c92ef4-4295-4e3c-84bf-c401e42105c4/devices/gateway/GW330027D1E9',
      name: 'Hub',
      serial_number: 'GW330027D1E9',
      state: {
        allow_bluetooth_lock: true,
        firmware_version: '1.7',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2021-08-28T19:44:22.3883323Z',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [ 'CG084690FD17', 'CG084690FD18' ],
        supports_dealer_diagnostics: false,
        updated_date: '2021-08-28T19:44:26.3964914Z',
        wifi_rssi_decibel_milliwatts: -50,
        wifi_signal_strength: 'excellent'
      }
    }
  ]
}
```

**Comment by marcelgood** [comment]
Looks like the myQ cloud is once again crapping out today, but I'm occasionally seeing this in the log when it reconnects:

```
[myQ] myQ device family 'gateway' is not currently supported, ignoring: Hub (serial number: GW330027D1E9).
```

This seems new, but it's also barely holding a connection at the moment.

```
[30/08/2021, 14:05:14] [myQ] myQ API: Successfully connected to the myQ API.
[30/08/2021, 14:05:14] [myQ] {
  accounts: [
    {
      created_by: '91817c0f-bbde-4ade-9334-ce91b187a4fe',
      id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      max_users: { co_owner: 2, guest: 5 },
      name: 'My Home'
    }
  ]
}
[30/08/2021, 14:05:14] [myQ] myQ API: Connection has been reset.
[30/08/2021, 14:05:14] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[30/08/2021, 14:07:11] [myQ] myQ API: Successfully connected to the myQ API.
[30/08/2021, 14:07:12] [myQ] myQ API: Connection has been reset.
[30/08/2021, 14:07:12] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[30/08/2021, 14:09:13] [myQ] myQ API: Successfully connected to the myQ API.
[30/08/2021, 14:09:13] [myQ] {
  accounts: [
    {
      created_by: '91817c0f-bbde-4ade-9334-ce91b187a4fe',
      id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      max_users: { co_owner: 2, guest: 5 },
      name: 'My Home'
    }
  ]
}
[30/08/2021, 14:09:13] [myQ] myQ API: Connection has been reset.
[30/08/2021, 14:09:13] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[30/08/2021, 14:11:13] [myQ] myQ API: Successfully connected to the myQ API.
[30/08/2021, 14:11:14] [myQ] myQ API: Connection has been reset.
[30/08/2021, 14:11:14] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[30/08/2021, 14:13:14] [myQ] myQ API: Successfully connected to the myQ API.
[30/08/2021, 14:13:14] [myQ] {
  accounts: [
    {
      created_by: '91817c0f-bbde-4ade-9334-ce91b187a4fe',
      id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      max_users: { co_owner: 2, guest: 5 },
      name: 'My Home'
    }
  ]
}
[30/08/2021, 14:13:14] [myQ] myQ API: Connection has been reset.
[30/08/2021, 14:13:14] [myQ] myQ API: Unable to retrieve account information. Will retry later.
[30/08/2021, 14:15:15] [myQ] myQ API: Successfully connected to the myQ API.
[30/08/2021, 14:15:15] [myQ] {
  accounts: [
    {
      created_by: '91817c0f-bbde-4ade-9334-ce91b187a4fe',
      id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      max_users: { co_owner: 2, guest: 5 },
      name: 'My Home'
    }
  ]
}
[30/08/2021, 14:15:15] [myQ] {
  accounts: [
    {
      created_by: '91817c0f-bbde-4ade-9334-ce91b187a4fe',
      id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      max_users: { co_owner: 2, guest: 5 },
      name: 'My Home'
    }
  ]
}
[30/08/2021, 14:15:16] [myQ] {
  count: 2,
  items: [
    {
      account_id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      created_date: '0001-01-01T00:00:00',
      device_family: 'garagedoor',
      device_model: 'virtualgaragedooropener',
      device_platform: 'myq',
      device_type: 'virtualgaragedooropener',
      href: '/accounts/d3c92ef4-4295-4e3c-84bf-c401e42105c4/devices/garagedoor/CG084690FD17',
      name: 'Garage',
      parent_device_id: 'GW330027D1E9',
      serial_number: 'CG084690FD17',
      state: {
        absolute_cycle_count: 0,
        attached_camera_serial_number: '',
        door_state: 'closed',
        dps_battery_critical: false,
        dps_low_battery_mode: false,
        dps_no_communication: false,
        is_scheduling_allowed: true,
        is_unattended_close_allowed: true,
        is_unattended_open_allowed: true,
        last_status: '2021-08-30T21:14:21.0521426Z',
        last_update: '2021-08-30T20:58:48.4523005Z',
        monitor_only_mode: false,
        number_of_learned_dps_devices: 1,
        online: true,
        sensor_comm_error: false,
        service_cycle_count: 0
      }
    },
    {
      account_id: 'd3c92ef4-4295-4e3c-84bf-c401e42105c4',
      created_date: '0001-01-01T00:00:00',
      device_family: 'gateway',
      device_model: 'hub',
      device_platform: 'myq',
      device_type: 'hub',
      href: '/accounts/d3c92ef4-4295-4e3c-84bf-c401e42105c4/devices/gateway/GW330027D1E9',
      name: 'Hub',
      serial_number: 'GW330027D1E9',
      state: {
        allow_bluetooth_lock: true,
        firmware_version: '1.7',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2021-08-30T20:58:19.3029459Z',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [ 'CG084690FD17', 'CG084690FD18' ],
        supports_dealer_diagnostics: false,
        updated_date: '2021-08-30T20:58:19.3038835Z',
        wifi_rssi_decibel_milliwatts: -45,
        wifi_signal_strength: 'excellent'
      }
    }
  ]
}
[30/08/2021, 14:15:16] [myQ] myQ API: Discovered device family garagedoor: Garage (serial number: CG084690FD17, gateway: GW330027D1E9).
[30/08/2021, 14:15:16] [myQ] myQ API: Discovered device family gateway: Hub (serial number: GW330027D1E9).
[30/08/2021, 14:15:16] [myQ] Garage: Door position sensor detected. Enabling battery status support.
[30/08/2021, 14:15:16] [myQ] myQ device family 'gateway' is not currently supported, ignoring: Hub (serial number: GW330027D1E9).
[30/08/2021, 14:15:16] [myQ] Garage: Closed.
[30/08/2021, 14:15:19] [myQ] myQ API: Connection has been reset.
[30/08/2021, 14:15:19] [myQ] myQ API: Unable to retrieve account information. Will retry later.
```

It's a shame really that the myQ is so unreliable. I've decided to order the Chamberlain hardware bridge. I understand that some people have issues with it as well, but I gonna give it a try. I appreciate the effort behind this plugin, but I think it's just kinda DOA if it has to rely on the unreliable myQ cloud. My understanding is the hardware bridge talks directly to the garage door opener, so the cloud isn't a factor. At least I'm hoping that's the case. At least I've got a strong WiFI signal at the new mounting location of the hub.

**Comment by marcelgood** [comment]
Just restarted homebridge again and now it happily discovered the gateway. So sometimes it discovers it fine, but other times it says it's not supported. 

```
[30/08/2021, 14:28:56] [myQ] myQ API: Discovered device family gateway: Hub (serial number: GW330027D1E9).
```

**Comment by jlg89** [comment]
Yeah, I just dropped the cash for one of their (overpriced) HomeKit bridges as well, hoping the same thing. The myQ cloud is just trash, they break their own app for crying out loud. If they'd just publish a local-connection API so things like homebridge-myq could talk to the hardware on the local network, they could eliminate all this craziness. At our old house, I slapped a re-flashed $10 Sonoff-SV relay on the garage door button circuit, and it works more reliably than Chamberlain's big-dollar boondoggle.

**Comment by hjdhjd** [comment]
Life with the myQ API wouldn’t be as much fun with a local API. :smile:

I’ve got three of their “Home Bridge”s…they are a bit finicky on maintaining their WiFi connections, so they can occasionally flake out as well. And configuring the thing…let’s just say you get sick of pressing button 1 and button 2 a whole lot.

Still…it’s the only game in town for the closest thing you can get to a true realtime interface right now. That said, you can always look at stuff like the Meross Garage Door Openers…they’re HomeKit compatible and basically emulate a remote control…which is more than enough for most people too.

**Comment by marcelgood** [comment]
It seems myQ has indeed started to more aggressively block too frequent polling requests. As posted in issue #499 (now closed) I also increased the polling rate to 45 seconds and the connection is indeed much more stable now. I had to restart the myQ hub as well as it lost its connection, but things appear to be working for now. I still gets an occasional token error, but then reconnects and is happy. Will watch it over the next days to see if it remains stable, but it definitely appears they've started to block requests if they are too frequent.

**Comment by hjdhjd** [comment]
I wouldn’t attribute all things to a polling interval change. Correlation isn’t causation. Particularly since plenty of us aren’t having issues with the defaults. I also would be very reluctant to set a polling interval to 45 seconds…that’s trading one set of potential problems for another set of real problems. 

If you set the polling interval too high, you **will** miss garage door open and close events under certain circumstances. Namely if you open and close your garage door within that 45 second window, it won’t be caught by the plugin - from it’s perspective, the door state never changed.

**Comment by marcelgood** [comment]
Agreed, and it looks like it was coincidence. I went back to the default this morning and it's fine now. Just kinda goes back to the original issue. Polling is problematic to begin with. I opened this issue as it appears the plugin misses events even with the default 12 second interval.
