### ISSUE TITLE
MyQ enabled camera

### ISSUE THREAD

**Issue by p808u2** [hjdhjd/homebridge-myq#509]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

I have such a camera and would be interested to assist in making a nice integration with your already nice plugin.

**Comment by hjdhjd** [comment]
Thanks for reaching out - I appreciate it! Access to a myQ camera isn’t the primary limitation at the moment…I’ll review this functionality in the future, pending a few other things.
