### ISSUE TITLE
Adding support for garage door lights

### ISSUE THREAD

**Issue by Skywalker8510** [hjdhjd/homebridge-myq#534]
**Is your feature request related to a problem? Please describe:**
this is not a problem it does everything I want it to but I would love it if I could control the lights on my garage door with home kit

**Describe the solution you'd like:**
I would love it if you could add support for the lights in the garage doors and am willing to help test it out

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
Lights are already supported. RTFM. 😀

If you’re asking about something other than official myQ lights the rule of thumb is: if the myQ app supports it we can support it. Otherwise no such luck I’m afraid!

**Comment by Skywalker8510** [comment]
oh ok thanks
