### ISSUE TITLE
OS15 Siri Garage door not opening 

### ISSUE THREAD

**Issue by cdaniels77** [hjdhjd/homebridge-myq#535]
Since upgrading to OS15 when I ask Siri to open the garage door I have to confirm the command on iPhone. This never happen in the past. Is there a way to change this?

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:** 14.17.2
* **Homebridge-myQ Plugin Version. 2.7.1
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone and mini home pod OS15
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
This isn’t a plugin issue I’m afraid…I haven’t tried, but if that’s the case, it would be because iOS might now consider that a secure command that needs authorization. Good luck.
