### ISSUE TITLE
I got ahold of myQ branded camera.  It connected without any problems to MyQ. I already have your plug-in running in homebrdge, It would be great to tie this in

### ISSUE THREAD

**Issue by Kpinkerton42** [hjdhjd/homebridge-myq#549]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by derflr** [comment]
Have you gotten any feedback? Are they adding support for MYQ camera?

**Comment by torresdrew** [comment]
Anyone figured out if there is a way to get the camera working?
