### ISSUE TITLE
Request - MyQ Camera Support 

### ISSUE THREAD

**Issue by RacerDelux** [hjdhjd/homebridge-myq#574]
**Is your feature request related to a problem? Please describe:**
The plugin currently doesn’t support myQ Camreas.

**Describe the solution you'd like:**
Support for myQ camreas.

**Describe alternatives you've considered:**
No real alternatives exist to get a myQ camera to work with HomeKit.

**Additional context:**
Willing to test and help develop this new feature.

**Comment by RacerDelux** [comment]
Poking this to keep it from going stale.

**Comment by hjdhjd** [comment]
I’d like to add support for this at some point, but it’s not a priority at the moment.

**Comment by RacerDelux** [comment]
Got it, here to test when you get to it.
