### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by jayewyo** [hjdhjd/homebridge-myq#577]
See api error picture. 
![7FC0EBEF-9D4C-459D-AEA0-5353D693813D](https://user-images.githubusercontent.com/33705594/145224431-120a7fa2-ee64-414a-a3d5-2ae31f816d75.jpeg)

**Comment by jayewyo** [comment]
Please reopen this request as it looks like the api needs fixed and will eventually crash homebridge

**Comment by hjdhjd** [comment]
This isn't a bug. Working as designed.
