### ISSUE TITLE
Support MyQ Lock

### ISSUE THREAD

**Issue by maghrab** [hjdhjd/homebridge-myq#588]
**Is your feature request related to a problem? Please describe:**
MyQ lock is not supported

**Describe the solution you'd like:**
Support MyQ lock and allow lock/unlock. 

**Describe alternatives you've considered:**
Use MyQ app directly or completely change the lock. 

**Additional context:**
I can help add support and test it since I just installed a lock.

**Comment by maghrab** [comment]
Please assign it to me if you are okay with me working on it.

**Comment by deftdawg** [comment]
@maghrab Did you make any headway with this?
