### ISSUE TITLE
2.7.2 on HOOBS 4.1.70

### ISSUE THREAD

**Issue by SlasherKG** [hjdhjd/homebridge-myq#603]
**Describe The Problem:**
After updating from 2.7.1 logs now show "WARNING No plugins installed" for the bridge it is running on when starting up. Looking at the log during the upgrade, it immediately says "Failed to find plugin to handle accessory Garage Door".

Downgrading to 2.7.1 works immediately again.

**To Reproduce:**
Update to 2.7.2.

**Logs:**

**Homebridge Configuration:**

**Screenshots:**

**Environment:**
Raspberry Pi 3 Model B Rev 1.2

* **Homebridge Version:** HOOBS 4.1.70 (Homebridge 1.3.8)
* **Node Version:** 16.13.1
* **Homebridge-myQ Plugin Version**: 2.7.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 Pro Max iOS 15.2
* **Operating System and OS Version:** Raspbian

**Comment by SlasherKG** [comment]
After the update todsy for both HOOBS 4.1.21 and myQ 2.7.3 everything seems to be working.

**Comment by hjdhjd** [comment]
Glad to hear it...as I don't use HOOBS, couldn't really tell you what the issue was I'm afraid.
