### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by csmyrnos** [hjdhjd/homebridge-myq#606]
**Describe The Problem:**

Starting a few days ago I’ve been receiving the following errors repeatedly:
[myQ] myQ API: Connection refused.
 [myQ] myQ API: Unable to access the OAuth authorization endpoint.

The garage door still appears in Homekit but the controls do not work and the status does not update when the door state changes.

I have not changed my login information to myQ and I can still access my garage door controls through the myQ app on my phone. I’ve tried resetting the device cache for the garage door and I’ve verified that my username and password are correct. Any ideas?

**To Reproduce:**
Install myQ plugin. Enter user name and password into config.json as described

**Logs:**

[myQ] myQ API: Connection refused.
 [myQ] myQ API: Unable to access the OAuth authorization endpoint.

**Homebridge Configuration:**

{
            "email": "email@email.com",
            "password": "password",
            "platform": "myQ"
        },

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** 12.22.7
* **Homebridge-myQ Plugin Version**: 2.7.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15
* **Operating System and OS Version:** Raspbian

**Comment by infinityflex** [comment]
Having same issue.

Homebridge Version: 1.4.0 beta 7
Node.js Version: 16.13.2
Homebridge-myQ Plugin Version: 2.7.3

**Comment by hjdhjd** [comment]
Occasional errors happen...this isn't a bug. It's just letting you know that the myQ API occasionally is less than reliable. :smile:
