### ISSUE TITLE
CarPlay interaction: control which door is displayed in CarPlay?

### ISSUE THREAD

**Issue by jdberry** [hjdhjd/homebridge-myq#607]
I have two garage doors. When I am close to my house, CarPlay displays one of the doors in the mixed view, which is great, as it potentially allows one-touch operation of the door. I recently re-configured MyQ, moving it to a child homebridge process. In the previous configuration, the correct door (the one I use) was always displayed in CarPlay. Now, with the new configuration, the incorrect door is always shown. I've been trying to be patient, hoping that Siri would figure out I'm using the other door, and change which one is displayed, but after weeks of waiting that doesn't seem to be happening.

Reading the interweb, it appears this is a common problem people have, and it doesn't appear Apple is using smarts to fix it at the moment.

Given that it was consistently one way previously, and is now consistently another way now, I'm assuming there's something consistent about the way in which the doors are being configured by the MyQ plugin that affects this issue. 

Maybe its:

1. The order in which the doors are registered or returned?
2. Perhaps this is based on some ordering of the unique ids, or the order in which they're stored in a registration database in HomeBridge?

My request is: Some means of configuring which door will be displayed. I realize it may not be obvious what it will take to affect that. If there were a way to at least say "this door is primary" that would be great. Perhaps that would control the order in which they're registered? The ordering of their unique id? I'm not sure...

Obviously, the right thing over time is for Apple to fix this so that it's correct per-phone, because (for instance) I might use one door while my house-mate uses another. But until that happens, it would be really nice to at least be able to make an affirmative selection.

Thoughts?

**To Reproduce:**

**Logs:**

**Homebridge Configuration:**

```json
{
    "email": "xxxxx",
    "password": "xxxxx",
    "platform": "myQ",
    "_bridge": {
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 123456
    }
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** v16.13.0
* **Homebridge-myQ Plugin Version**: 2.7.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15.1.1
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Let me point you to @iRayanKhan who uses this plugin with CarPlay every day...@iRayanKhan - can you shed a little light? 😄

**Comment by hjdhjd** [comment]
Try v5.0.4. The issue you're having is basically one you're creating for yourself in trying to open too many things too quickly...BUT...it's still a bug. :smile: Let me know how this one goes.

**Comment by iRayanKhan** [comment]
Hello 👋🏽 


It was quite the workaround, but I managed to get my desired Garage to show in car play by doing the following 

1) Uninstall the plugin (remember your deviceID's)

2) Remove the garages from HomeKit

3) Reset CarPlay in iOS settings and on your dash

4) Reinstall and configure the plugin (use a child bridges if utilizing Homebridge UI), but only for the desired deviceID

5) Pair bridge to HomeKit, verify only one garage has been added 

6) Open/Close the garage several times from the phone 

7) Don't connect phone to CarPlay *yet*, but drive about half a mile away from your home, then re-connect CarPlay, and on the way home the desired device should show up. Repeatedly open and close the garage from CarPlay

8) Pair the second garage in its own child bridge 

I have had CarPlay consistently show my garage for the past few months. 

Unfortunately you can't switch which garage per car, or user. This is such an obvious oversight from Apple I hope to see cleared.
