### ISSUE TITLE
Battery status not working

### ISSUE THREAD

**Issue by marcelgood** [hjdhjd/homebridge-myq#608]
**Describe The Problem:**
I just updated to the latest plug-in after updating Node.JS, and now the battery status no longer works. The accessories page says "null%" for the battery, and the Home app shows no battery status for my door sensor. 

**To Reproduce:**
Update Node.JS and update plug-in to latest version. Check accessories page and see battery percentage not being displayed. 

**Logs:**

Nothing really in the logs. It says battery status support is enabled. 
```
[10/01/2022, 09:43:34] [myQ] myQ API: Successfully connected to the myQ API.
[10/01/2022, 09:43:34] [myQ] myQ API: Discovered device family garagedoor: Garage (serial number: CG084690FD17, gateway: GW330027D1E9).
[10/01/2022, 09:43:34] [myQ] myQ API: Discovered device family gateway: Hub (serial number: GW330027D1E9).
[10/01/2022, 09:43:34] [myQ] Garage: Door position sensor detected. Enabling battery status support.
```

**Homebridge Configuration:**

```json
        {
            "email": "<removed>",
            "password": "<removed>",
            "debug": false,
            "platform": "myQ"
        },
```

**Screenshots:**

https://imgur.com/lIayHxM

**Environment:**

* **Homebridge Version:** v1.3.9
* **Node Version:** v16.13.1
* **Homebridge-myQ Plugin Version**:  v2.7.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 15.2
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)

**Comment by hjdhjd** [comment]
Thanks for catching this...I'll address in the next update.

**Comment by hjdhjd** [comment]
Also...screenshot if you don't mind?

**Comment by marcelgood** [comment]
I linked to the screenshot in the original post. https://imgur.com/lIayHxM

**Comment by donavanbecker** [comment]
@marcelgood, this is an [issue with Homebridge UI](https://github.com/oznu/homebridge-config-ui-x/issues/1269). Battery Status works correctly in MyQ Plugin. MyQ API, doesn't provide Battery Percentage and new the new [Battery](https://developers.homebridge.io/#/service/Battery) Service only requires Low Battery Status Characteristic, so that is all that is being used.
