### ISSUE TITLE
TypeError in 2.7.4 shutting down service

### ISSUE THREAD

**Issue by corey6058** [hjdhjd/homebridge-myq#619]
**Describe The Problem:**

Upon starting the service, I receive a Fatal error that shuts down the service as a result.

**To Reproduce:**

Start the service anytime after the new update with credentials in tact. I can remove my password from the configuration file to obviously skip authentication and thus never receive the error and keep my other accessories going.

**Logs:**

1/18/2022, 8:49:16 PM TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type number
at write_ (_http_outgoing.js:618:11)
at ClientRequest.write (_http_outgoing.js:586:15)
at Readable.ondata (_stream_readable.js:728:22)
at Readable.emit (events.js:223:5)
at addChunk (_stream_readable.js:309:12)
at readableAddChunk (_stream_readable.js:290:11)
at Readable.push (_stream_readable.js:224:10)
at next (internal/streams/from.js:34:27)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
1/18/2022, 8:49:16 PM Got SIGTERM, shutting down Bridge...

**Homebridge Configuration:**

{
            "platform": "myQ",
            "plugin_map": {
                "plugin_name": "homebridge-myq"
            },
            "email": "myemailhere@icloud.com",
           "password": "password123",
            "name": "Overhead Garage Door",
            "options": []
        }

**Screenshots:**

**Environment:**

* **Homebridge Version:** 3.3.12
* **Node Version:** 12.14.1
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Macbook Pro using browser GUI into HB
* **Operating System and OS Version:** Raspbian GNU/Linux

**Comment by hjdhjd** [comment]
That’s an odd one. Can you do me a favor and try uninstalling and reinstalling the plugin and see if that helps?

**Comment by corey6058** [comment]
I'm afraid it didn't solve it. When the plugin first installs, it starts the service fine although there aren't any login credentials set yet. if I update my username and password in the configuration file, it restarts the service and I end up with the same error as above and it shuts down.

**Comment by hjdhjd** [comment]
Can you manually downgrade versions and see what the last working version is for you? Nothing has changed of substance in the code aside from some dependency updates.

**Comment by hjdhjd** [comment]
There’s also no such Homebridge version as 3.3.12….

**Comment by hjdhjd** [comment]
I’m going to guess you are running HOOBS, which is based on Homebridge but not exactly Homebridge…if you are…then I’m afraid there’s not much I can help you with here…you need to reach out to the HOOBS folks on the errors you’re seeing.

**Comment by corey6058** [comment]
You are correct that I’m using HOOBS. And that version I provided was the version of HOOBS I currently have. I’ll see if I can downgrade a version or so. Thank you for your time

**Comment by hjdhjd** [comment]
Anytime…sorry I can’t be more helpful to you here!
