### ISSUE TITLE
AppleID Login

### ISSUE THREAD

**Issue by cardinalsfan** [hjdhjd/homebridge-myq#651]
**Describe The Problem:**
I used my AppleID to set up my MyQ account on the app.  I can log in to the app to see the fake email it uses but have no idea how to view/change the password.  

**To Reproduce:**
Attempt to create MyQ account using AppleID then login to MyQ.  

**Logs:**
None, no password to even enter in this plugin to attempt to get logs.  

**Homebridge Configuration:**

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.0
* **Homebridge-myQ Plugin Version**:2.7.4

**Comment by hjdhjd** [comment]
Apple ID based login credentials are not, and will not be, supported any time soon (as in maybe not for years). My strong recommendation is to instead use something like Apple's Hide My Email instead and use that coupled with a password. Thanks for calling it to my attention!

**Comment by cardinalsfan** [comment]
> Apple ID based login credentials are not, and will not be, supported any time soon (as in maybe not for years). My strong recommendation is to instead use something like Apple's Hide My Email instead and use that coupled with a password. Thanks for calling it to my attention!

Good idea, I'll see if I can transfer my MyQ gateway to a new account.  I can't use my old account because it won't let me remove my old house and garage door.  

Thank you for the amazingly fast response, sorry if i missed this detail in the documentation somewhere!

**Comment by hjdhjd** [comment]
You most certainly didn't miss it! It's a relatively new myQ login option...and I've been a bit busy elsewhere. :smile: It's never-ending keeping up with this stuff!

You should be able to transfer accounts...it's essentially unregister all your gateways and re-register them under a new account. Best of luck!
