### ISSUE TITLE
Double accessories showing

### ISSUE THREAD

**Issue by rladelman771** [hjdhjd/homebridge-myq#660]
Describe The Problem:
Updated to latest plugin.  Second set have null% instead of garage picture. Everything seems to be working. Can’t delete them or remove them.  They are stuck in default room

To Reproduce:
Restart homebridge

Logs:
n/a

Homebridge Configuration:

{
    "bridge": {
        "name": "Homebridge 0381",
        "username": 
        "port": 
        "pin": 
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "email": 
            "password": 
            "platform": "myQ"
        },
        {
            "name": "TplinkSmarthome2",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "excludeMacAddresses": [
                "10:27:F5:3E:75:E5"
            ],
            "devices": [
                {
                    "host": "10.20.30.227"
                },
                {
                    "host": "10.20.30.228"
                },
                {
                    "host": "10.20.30.229"
                },
                {
                    "host": "10.20.30.231"
                },
                {
                    "host": "10.20.30.232"
                },
                {
                    "host": "10.20.30.233"
                },
                {
                    "host": "10.20.30.234"
                },
                {
                    "host": "10.20.30.235"
                },
                {
                    "host": "10.20.30.237"
                },
                {
                    "host": "10.20.30.238"
                },
                {
                    "host": "10.20.30.239"
                },
                {
                    "host": "10.20.30.240"
                },
                {
                    "host": "10.20.30.241"
                },
                {
                    "host": "10.20.30.242"
                },
                {
                    "host": "10.20.30.243"
                },
                {
                    "host": "10.20.30.236"
                },
                {
                    "host": "10.20.30.244"
                },
                {
                    "host": "10.20.30.225"
                }
            ],
            "platform": "TplinkSmarthome"
        }
    ]
}

Environment:
* Homebridge Version: 1.4.0
* Node Version: v17.4.0
* Homebridge-myQ Plugin Version: 2.7.4
* iPhone 12 pro and pro max and iOS / macOS / iPadOS / tvOS Version: iPhone 13 pro and pro max running 15.3.1
* Operating System and OS Version: raspberry pi debian
![D46B334D-EAB9-4573-B62E-3AFA0E6E2AE7](https://user-images.githubusercontent.com/63269374/155891092-3ee9bd83-874d-4a10-aa83-7b48b2d8e2e8.png)
![AFE62568-3EE4-425B-BE1E-A8B20ED6DE82](https://user-images.githubusercontent.com/63269374/155891094-8cf3796f-7388-49a4-b4be-a57576ae0334.png)

**Comment by rladelman771** [comment]
bump

**Comment by hjdhjd** [comment]
Not my bug. Your issue is with the Homebridge webUI, not this plugin. :smile:
