### ISSUE TITLE
MyQ 2.7.4 Fails Authentication in Hoobs

### ISSUE THREAD

**Issue by jlenkows** [hjdhjd/homebridge-myq#686]
**Describe The Problem:**
After rebuilding my HOOBS from scratch due to a failed SD card, when I install MyQ and enter verified credentials, I get an error in the log stating "myQ BridgemyQ ERROR myQ API: Invalid myQ credentials given. Check your login and password.". I have verified the credentials are indeed correct and valid by logging into both the MyQ app and website.

**To Reproduce:**
The error continuously repeats in the log. No steps needed to reproduce.

**Logs:**
4/1/2022, 11:38:48 AMmyQ BridgeLoaded plugin 'homebridge-myq'
4/1/2022, 11:38:48 AMmyQ BridgeLoading 1 platforms...
4/1/2022, 11:38:48 AMmyQ BridgemyQERRORNo myQ login credentials configured.
4/1/2022, 11:38:48 AMmyQ BridgeBridge is running on port 51886.
4/1/2022, 11:38:48 AMmyQ BridgeConfiguration change
4/1/2022, 11:38:48 AMmyqbridge stopping
4/1/2022, 11:38:54 AMmyQ Bridge starting
4/1/2022, 11:38:59 AMmyQ BridgeLoaded plugin 'homebridge-myq'
4/1/2022, 11:38:59 AMmyQ BridgeLoading 1 platforms...
4/1/2022, 11:39:00 AMmyQ BridgeBridge is running on port 51886.
4/1/2022, 11:39:00 AMmyQ BridgemyQERRORmyQ API: Invalid myQ credentials given. Check your login and password.
4/1/2022, 11:41:01 AMmyQ BridgemyQERRORmyQ API: Invalid myQ credentials given. Check your login and password.
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
{
    "platform": "myQ",
    "email": "xxxxx@xxxxxx.xxx",
    "password": "xxxxxxxxx"
}
```

**Screenshots:**

**Environment:**

* **Hoobs Version:** 4.2.1
* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.2
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 iOS 15.4, MacOS 12.3
* **Operating System and OS Version:** 
*hoobs@hoobs:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by asander85** [comment]
Why was this invalid? Nobody ever answered his question. I am currently having the same issue exactly.
