### ISSUE TITLE
Only 1 of 2 garage doors work via myQ HomeBridge Plugin (1 Hub, 2 sensors)

### ISSUE THREAD

**Issue by tf64** [hjdhjd/homebridge-myq#713]
**Describe The Problem:**
1 of 2 garage doors will not open/close via HomeKit using myQ Homebridge plugin. Both are detected in HomeKit, one opens/closes properly, the other will not function. Both garage doors open/close properly when using the Native iOS myQ app or using standard OEM remote. Log error from Homebridge below (note the same error posts for both doors)

**To Reproduce:**
1) Installed Homebridge v. 1.4.1 (Hoobs v 4.2.5), node version 16.15.0, myQ v2.7.4. 2) Configured myQ plugin using visual method with email and password.  3) Added bridge to HomeKit using QR code scan.  4) Command door open via HomeKit app. Note two garage doors are working through a single MyQ Hub using 2 door sensors.

**Logs:**

```

5/8/2022, 11:26:07 AMmyQERROR[myQ D21E@Name's Garage Door@Name's Garage Door@Target Door State] SET handler returned write response value, though the characteristic doesn't support write response
```

**Homebridge Configuration:**

{
    "accessories": [],
    "platforms": [
        {
            "platform": "myQ",
            "email": "myemail@email.com",
            "password": "my_myQ_password"
        }
    ]
}

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.4.1
* **Node Version:** 16.15.0
* **Homebridge-myQ Plugin Version** 2.7.4. 2-
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone iOS 15.4.1
* **Operating System and OS Version:**  macOS 12.3.1

**Comment by hjdhjd** [comment]
Thanks for the report. The error message is harmless - it'll disappear in the next release.

You need to post the **entirety** of the myQ-related log messages and more fully and completely describe your garage door opener setup (models, myQ hubs, etc).

I have a similar setup that works without issue...not much consolation, I understand, but let's figure out what's going on here and get you up and running.
