### ISSUE TITLE
400 Bad Request Error

### ISSUE THREAD

**Issue by Sirgrant618** [hjdhjd/homebridge-myq#745]
**Describe The Problem:**
Starting about a week ago (+/-) I started getting this error:
400 Bad Request; Unable to retrieve account information.

**To Reproduce:**
Run the plugin

**Logs:**

```
[6/6/2022, 3:24:55 PM] [Garage Door] myQ API: Successfully connected to the myQ API.
[6/6/2022, 3:24:55 PM] [Garage Door] myQ API: https://accounts.myq-cloud.com/api/v6.0/accounts Error: 400 Bad Request
[6/6/2022, 3:24:55 PM] [Garage Door] myQ API: Unable to retrieve account information.
```

**Homebridge Configuration:**

```json
        {
            "email": "------@gmail.com",
            "password": "*********",
            "name": "Garage Door",
            "options": [
                "Disable.CG***********"
            ],
            "platform": "myQ"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.4.1
* **Node Version:** v16.13.2
* **Homebridge-myQ Plugin Version**: v2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15.5
* **Operating System and OS Version:** macOS 11.2.3

**Troublshooting**
* Restart Homebridge instance and server
* reset myQ password

**Comment by hjdhjd** [comment]
myQ API errors happen...the API can be flaky at times. It's particularly egregious around month-end/beginning unfortunately.

The API is working - I, and others, have no issues. I'd wait this out...if this issue persists for another week or two, happy to take another look. Meanwhile, you might want to change your password...that can occasionally force things to be cleaned up on the server end.

Best of luck - wish I had something more useful to share.

**Comment by Sirgrant618** [comment]
Thanks for replying. Yeah, changed my password, but will see what happens.

Thanks again!

**Comment by Sirgrant618** [comment]
Apologies, one more thing. When you say the API can be flakey, do you
literally mean it just can stop working for a bit for no identifiable
reason and then start up again? Just curious.

Thanks!

**Comment by hjdhjd** [comment]
Yes, as is well-documented in many previous issues, and the [README](https://github.com/hjdhjd/homebridge-myq#things-to-be-aware-of) for this plugin. 😄 They're a garage door opener company, not a digital-native Silicon Valley one...
