### ISSUE TITLE
how to run disable.serialnumber

### ISSUE THREAD

**Issue by zzack01** [hjdhjd/homebridge-myq#790]
**Describe The Problem:**

Please help me figure out how to get the below to work, It is currently not working:

I have changed my email to email, my password to password, my serial number (according to myq app) to serialnumber

Disable.serialnumber - hide the opener or gateway identified by serialnumber from HomeKit.

{
"platform": "myQ",
"email": "email",
"password": "password",
"name": "MyQ",
"options": [
"disable.serialnumber"
]
}

**To Reproduce:**

above is the configuration
**Logs:**

N/a
```
Show the Homebridge logs here.
Remove any sensitive information.
`.`.`

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by zzack01** [comment]
Please submit an answer before this closes.

**Comment by zzack01** [comment]
Please submit an answer before this closes.

**Comment by zzack01** [comment]
Hello,

Still awaiting a response, please submit the answer before this closes

**Comment by hjdhjd** [comment]
Documentation is here: https://github.com/hjdhjd/homebridge-myq/blob/master/docs/FeatureOptions.md

The serial number will be enumerated in the Homebridge logs for the plugin, and they are also in the details of the garage door opener in the Home app. If you are uncertain about any of the above, you can ask on the Homebridge Discord. Thanks!

**Comment by zzack01** [comment]
In the advanced code should it read 
{
"platform": "myQ",
"email": "email",
"password": "password",
"name": "MyQ",
"options": [
"disable.serialnumber123456789" or "disable.123456789" or "disable": "123456789"
]
}

I have tried all the possible combinations and it is still not working

**Comment by zzack01** [comment]
Can you please give an example of this

**Comment by zzack01** [comment]
Do I need the <> or just type the number?

**Comment by gschivley** [comment]
Just the serial number. < and > are usually used to show the place you put your own value in.
