### ISSUE TITLE
Unable to Open or Close Using Siri

### ISSUE THREAD

**Issue by xytras78** [hjdhjd/homebridge-myq#801]
**Describe The Problem:**
I'm having an issue in that Siri is unable to control my garage doors. She can't open or close them, though she reports that she did so just fine... always responding "Done!" Using the Home app on either iOS/iPadOS or MacOS, I'm able to control the doors perfectly with zero issue.

I'm using the old original Liftmaster Hub, 828LM Internet Gateway. Thanks in advance!

**To Reproduce:**
I have two garage doors configured in homebridge-myq, "Right Garage Door" and "Left Garage Door." If I say "Siri, open right garage door," she will respond within seconds saying "Done!" yet nothing happens.

**Logs:**
Nothing pertaining to MyQ is in the logs.

**Homebridge Configuration:**

Nothing relevant in the config other than to disable a GW device.  Problem exists with or without that.

**Screenshots:**
Not applicable.  Issue is verbal.

**Environment:**

* **Homebridge Version:** 1.5
* **Node Version:** 16.16
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15.5 on iPhone 13 Pro
* **Operating System and OS Version:** macOS 12.5

**Comment by xytras78** [comment]
Anyone?  Any thoughts at all?  No matter what I do, Siri does not function with this plugin. Every other one works great… just not this one. Thanks!!!

**Comment by hjdhjd** [comment]
This isn’t a plugin issue - this is a Siri issue…if and when the plugin receives a command from HomeKit it gets executed, which you can do without an issue in the Home app it seems. There’s not much else we can do here - it’s a bit of a black box on the Apple end. You may want to try the usual litany of rebooting HomePods and Apple TV’s and see if it helps, but as I stated - there’s nothing here to be done on the plugin end of the spectrum. Best of luck!

**Comment by jvanderaa** [comment]
The reboot option is indeed a good thing to go for. I had issues and found this issue. They were resolved after rebooting all of the hubs in the environment.
