### ISSUE TITLE
Logging in with SSO

### ISSUE THREAD

**Issue by anotherjohnwong** [hjdhjd/homebridge-myq#810]
**Describe The Problem:**
My myQ account is created and accessed through AppleID SSO, there is no username and password so unable to sign in via the Homebridge plug-in.

**To Reproduce:**
Use a myQ account created with any password-less SSO method.

**Logs:**

```
8/11/2022, 10:05:15 PMmyQ Bridge starting
8/11/2022, 10:05:45 PMmyQ BridgeLoaded plugin 'homebridge-myq'
8/11/2022, 10:05:45 PMmyQ BridgeLoading 1 platforms...
8/11/2022, 10:05:45 PMmyQ BridgemyQERRORNo myQ login credentials configured.
```

**Homebridge Configuration:**

```json
{
    "platform": "myQ",
    "email": "----------@privaterelay.appleid.com"
}
```

**Screenshots:**

N/A

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.16.0
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** macOS, iPhone (all latest)
* **Operating System and OS Version:** HOOBS 4.2.8

**Comment by hjdhjd** [comment]
Thanks, SSO logins are unsupported by this plugin.
