### ISSUE TITLE
Disable Battery Status config option

### ISSUE THREAD

**Issue by matts07** [hjdhjd/homebridge-myq#819]
**Is your feature request related to a problem? Please describe:**
No problem exists in homebridge-myq plugin. MyQ 'Low battery' status still exists months after changing battery in door position sensor and therefore persists in Homebridge showing a battery warning constantly in Homekit.

**Describe the solution you'd like:**
Add "Disable Battery Status" as a Plugin Feature Option.

**Describe alternatives you've considered:**
None

**Additional context:**
Thanks for the consideration!

**Comment by hjdhjd** [comment]
It is in the backlog for a future release. Thanks for the feedback.
