### ISSUE TITLE
Battery status in Homekit

### ISSUE THREAD

**Issue by batracy** [hjdhjd/homebridge-myq#846]
**Describe The Problem:**
I'm not seeing the battery status in Homekit, it does show up in  ControllerForHomekit. Is this normal, because I thought the battery status was supposed to show in Homekit? Or maybe I'm not understanding how this is supposed to work.

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
```

**Homebridge Configuration:**
Default - used the UI to configure

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.15.1
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**Late 2014 Mac Mini, macOS Monterey 12.5
* **Operating System and OS Version:** macOS Monterey 12.5

**Comment by carlosgamezvillegas** [comment]
I would like to know the answer for this too

**Comment by hjdhjd** [comment]
Battery status in HomeKit doesn’t show a “battery meter”, but rather an alert status message when the battery is **low**. If you don’t see a status, it’s because your battery is fine. 😄
