### ISSUE TITLE
Add camera support 

### ISSUE THREAD

**Issue by carlosgamezvillegas** [hjdhjd/homebridge-myq#856]
**Is your feature request related to a problem? Please describe:**

Now more chamberlain garage door openers come with a camera. Is there a plan bring the video feed to HomeKit?

**Describe the solution you'd like:**

I would like to see the camera feed from the Home app.

**Describe alternatives you've considered:**

Open the MyQ app

**Additional context:**

None

**Comment by hjdhjd** [comment]
As you can see in prior issues…it’s on the backlog. Thanks!
