### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by usmcfiredog** [hjdhjd/homebridge-myq#859]
**Is your feature request related to a problem? Please describe:**

No problem with the plugin itself.

**Describe the solution you'd like:**

A way to encrypt passwords in the config file, so that passwords to accounts are not stored in the clear in the config file

**Describe alternatives you've considered:**

No other alternatives considered

**Additional context:**

Get rid of account passwords that are in the clear in the configuration file.

**Comment by hjdhjd** [comment]
Thanks, but this wouldn’t really accomplish much other than obfuscate passwords. Appreciate the input!

**Comment by usmcfiredog** [comment]
yes it would obfuscate that but it would make it harder for someone to get an account password if they happened to gain access to the system.

**Comment by hjdhjd** [comment]
If someone gained access to your homebridge install you’ve got far larger problems. 😄 Thanks for the input!
