### ISSUE TITLE
Random Garage Open/Close Notifications Without Action

### ISSUE THREAD

**Issue by CaptBeard** [hjdhjd/homebridge-myq#879]
**Describe The Problem:**
It seems just about a few times a week I'll get an alert from Apple Home that my one garage door has opened and closed. (It's the same door each time, I have two doors in MyQ) The door doesn't actually move and has not been triggered by MyQ or Home. Both Homebridge and MyQ reflect that the door has moved recently, but a camera on the door disproves this.
Has been happening for months, and finally had the time to report it.

**To Reproduce:**
Wait for behavior above to happen. Most recently happened at 11:01 on day of writing this.

**Logs:**

```
[11/10/2022, 11:01:56] [myQ] Black: Opening.
[11/10/2022, 11:02:17] [myQ] Black: Closed.
```

**Homebridge Configuration:**

```json
"platforms:" [
  {
            "email": "email@gmail.com",
            "password": "Super-Secure-Password!",
            "platform": "myQ"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.14.2
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 14 Pro Max 16.1
* **Operating System and OS Version:** Raspbian 11

**Comment by hjdhjd** [comment]
Appreciate the report - unfortunately, all we do is report what myQ is seeing…there’s not much I can do on the plugin end for this if myQ is receiving/sending bad information. Haven’t seen a hardware/myQ issue like this one come across before, so I’m curious to see what you discover.

Sorry I can’t be more helpful here.
