### ISSUE TITLE
Camera Integration question

### ISSUE THREAD

**Issue by gregpa** [hjdhjd/homebridge-myq#882]
**Describe The Problem:**
Can you comment on this? 
"myQ cameras may be added at some point, but there are additional non-technical considerations related to the paid myQ product that I want to be mindful of."
This is a much needed feature.  If it can be done technically, I do not see what the issue is that would cause this to be on pause.
Thank you

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-myQ Plugin Version**:
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Please don’t open issues seeking comment - issues are for bug reports or feature requests. I’ve got nothing to add to my remarks. Thanks. The place for discussion is the Homebridge Discord, not an issue tracker. Please respect how I’ve chosen to manage the issues tracker for this project.
