### ISSUE TITLE
Update for LTS Node 18.x

### ISSUE THREAD

**Issue by Blackfish95** [hjdhjd/homebridge-myq#912]
**Describe The Problem:**
Latest version of MyQ plugin does not like the LTS v18 of NODE
Error:
The plugin "homebridge-myq" requires Node.js version of ^14.18.1 || ^16.13.0 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

**To Reproduce:**
Run homebridge-myq on node 18.12.1
**Logs:**
The plugin "homebridge-myq" requires Node.js version of ^14.18.1 || ^16.13.0 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.5.1
* **Node Version:** 18.12.1
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:** Windows

**Comment by hjdhjd** [comment]
There will be a future update to address this. Thanks!
