### ISSUE TITLE
Node.js is out of date.

### ISSUE THREAD

**Issue by mbierman** [hjdhjd/homebridge-myq#923]
**Describe The Problem:**
The following error now shows in current homebridge. 
```
The plugin "homebridge-myq" requires Node.js version of ^14.18.1 || ^16.13.0 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```

**To Reproduce:**
Install this pluigin with current homebridge.

Changing `package.json` to

```
 "engines": {
    "homebridge": ">=1.3.9",
    "node": "^14.18.1 || ^18.11.1"
```

seems to solve it.  Nothing seems to break.

**Logs:**
see above. 

**Homebridge Configuration:**

* **Node.js Version**: 18.12.1
* **Homebridge Version**: 1.5.1
* **Homebridge Config UI X Version**: v4.50.2
* **Operating System**: Docker
* **Process Supervisor**: Docker 
* **Ubuntu Linux**: 20.04.5LTS

**Screenshots:**

**Environment:**

* **Homebridge Version:**1.6.0
* **Node Version:** v18.12.1
* **Homebridge-myQ Plugin Version**: v2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Not relevant
* **Operating System and OS Version:** Docker

**Comment by randymassey** [comment]
I see this in my logs as well, but functionally I have no issues or errors as a result.  Plug-in works flawlessly in my setup.RandySent from my iPhoneOn Nov 29, 2022, at 1:07 PM, Michael Bierman ***@***.***> wrote:﻿


Describe The Problem:
The following error now shows in current homebridge.
The plugin "homebridge-myq" requires Node.js version of ^14.18.1 || ^16.13.0 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

To Reproduce:
Install this pluigin with current homebridge.
Logs:
see above.
Homebridge Configuration:

Node.js Version: 18.12.1
Homebridge Version: 1.5.1
Homebridge Config UI X Version: v4.50.2
Operating System: Docker
Process Supervisor: Docker
Ubuntu Linux: 20.04.5LTS

Screenshots:

Environment:

**Homebridge Version:**1.6.0
Node Version: v18.12.1
Homebridge-myQ Plugin Version: v2.7.4
Apple Device and iOS / macOS / iPadOS / tvOS Version: Not relevant
Operating System and OS Version: Docker

**Comment by mbierman** [comment]
> I see this in my logs as well, but functionally I have no issues or errors as a result.  Plug-in works flawlessly in my...

Agreed, but I don't like to see errors. I updated the package.json and the update seems to have worked so I created a pull request to silence this noise.

**Comment by hjdhjd** [comment]
Thanks but there will be a future update to address this and other things. Thanks again.

**Comment by mbierman** [comment]
No worries, @hjdhjd ! Glad to hear there will be updates coming. I was getting nervous.

**Comment by hjdhjd** [comment]
I promise it only looks like there’s little activity going on here or my other plugins…in reality, been quietly working in my little free time on a few things. I just prefer to wait until they’re well-tested by yours truly…and I’m around for the inevitable support tsunamis that occur. 😄 I’m overdue for a maintenance update here…it’s coming.

✌️
