### ISSUE TITLE
Plugin needs to be updated for more current node.js versions

### ISSUE THREAD

**Issue by jonnyborbs** [hjdhjd/homebridge-myq#929]
**Describe The Problem:**
Plugin does not support modern versions of node.js, using a regex that looks explicitly for 14 or 16

**To Reproduce:**
Upgrade to node.js v18

**Logs:**
```
[03/12/2022, 18:53:511 The plugin "homebridge-myg" requires Node. js version of ^14.18.1 || ^16
.13.0 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```

**Homebridge Configuration:**

Nothing special to report here

**Screenshots:**
Log above shows the full detail

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 18.12.1
* **Homebridge-myQ Plugin Version**: 2.7.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Not relevant but iOS 16.1.2
* **Operating System and OS Version:** Not relevant but iOS 16.1.2

**Comment by hjdhjd** [comment]
Already notes in prior issues related to this. Technically, it does support modern versions of Node…just not v18. That said, this is a harmless error. A future update will address the error.
