### ISSUE TITLE
MyQ garage opener not detected as accessory by "Homebridge Google Smart Home" plugin

### ISSUE THREAD

**Issue by bbatod** [hjdhjd/homebridge-myq#946]
**Is your feature request related to a problem? Please describe:**

When you add "Homebridge Google Smart Home" plugin to control the Homebridge accessories with Google Home, the garage door opener does not get added as an accessory that I can control with Google Home. 

It looks like it is because the garage opener is not listed under "accessories" in the configuration instead it is listed under "platforms". 

**Describe the solution you'd like:**

Is it possible to have the garage opener listed under accessories so that "Homebridge Google Smart Home" detects the garage opener accessory?

**Describe alternatives you've considered:**

Not sure if this is something "Homebridge to Google Home" needs to fix on their end to detect devices listed under "platforms"

**Additional context:**

Garage opener works perfect with HomeKit. I wanted to make it work with Google Home since I have some Home Mini and Nest Mini speakers.

**Comment by hjdhjd** [comment]
Sorry but I don’t support the Homebridge Google Smart Home plugin. You might want to try opening an issue in their support channel. I only provide support for my plugins, I’m afraid. Best of luck.
