### ISSUE TITLE
myQ API: Hostname or IP address not found

### ISSUE THREAD

**Issue by antonybasta** [hjdhjd/homebridge-myq#956]
**Unable to connect to MyQ API using homebridge**

Get the following: 
myQ API: Unable to retrieve account information.
myQ API: Hostname or IP address not found.

**To Reproduce:**
Open or close any garage door

**Logs:**

```
[22/12/2022, 14:28:34] [myQ] myQ API: Hostname or IP address not found.
[22/12/2022, 14:28:34] [myQ] myQ API: Unable to retrieve account information.
[22/12/2022, 14:28:44] [myQ] myQ API: Hostname or IP address not found.
[22/12/2022, 14:28:44] [myQ] myQ API: Unable to send the command to myQ servers. Acquiring a new access token.
```

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** v18.12.
* **Homebridge-myQ Plugin Version**: 2.8.1
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Nope. 

Appreciate the report, but not the conclusion. People are always quick to conclude that the API has changed when it’s really just occasional / ongoing flakiness in their API. This should resolve itself, I suspect.

Feel free to see for yourself: https://dns-lookup.com/partner-identity.myq-cloud.com

Thanks again!

**Comment by Danimal4326** [comment]
Try forcing the api to use the "west" servers.  
You'll need to manually edit the following file: (note your path may vary)
/usr/lib/node_modules/homebridge-myq/node_modules/@hjdhjd/myq/dist/myq-api.js

Change all urls to use the "west" zone
* partner-identity-west.myq-cloud.com
* devices-west.myq-cloud.com
* accounts-west.myq-cloud.com
* account-devices-lamp-west.myq-cloud.com
* account-devices-gdo-west.myq-cloud.com

Save the file, restart homebridge, and it should be much better.
