### ISSUE TITLE
Base64 Encryption Support for Plugin Password

### ISSUE THREAD

**Issue by LeoOttawa** [hjdhjd/homebridge-myq#962]
**Is your feature request related to a problem? Please describe:**
Add Base64 support for the plugin password.  The myQ plugin password is in plain text and visible in the config.json file or directly in the Homebridge configuration editor. 

**Describe the solution you'd like:**
Ability for the plugin to decrypt Base64 passwords saved in the config.json file.

**Describe alternatives you've considered:**
None

**Additional context:**
Example - Current
{
"name": "myQ",
"username": "[yourmail@domain.com](mailto:yourmail@domain.com)",
"password": "HelloWorld1234",
"platform": "myQ"
}

Example - hidden password in base64
{
"name": "myQ",
"username": "[yourmail@domain.com](mailto:yourmail@domain.com)",
"password": "SGVsbG9Xb3JsZDEyMzQK",
"platform": "myQ"
}

**Comment by hjdhjd** [comment]
Appreciate the request, but I won’t be implementing this.
