### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by nyjklein** [hjdhjd/homebridge-myq#964]
**Describe The Problem:**

Updated to v2.8.2 now getting: [myQ] myQ API: Invalid myQ credentials given. Check your login and password.
**To Reproduce:**

Updated plugin, restarted. Nothing else changed! Hadn't updated credentials in a long time.
**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```
[27/12/2022, 17:22:29] Registering platform 'homebridge-myq.myQ'
[27/12/2022, 17:22:34] [myQ] Initializing myQ platform...
[27/12/2022, 17:22:34] [myQ] Debug logging on. Expect a lot of data.
[27/12/2022, 17:22:38] [myQ] myQ API: Invalid myQ credentials given. Check your login and password.

This is what the log looked like earlier today:
[27/12/2022, 12:42:34] Registering platform 'homebridge-myq.myQ'
[27/12/2022, 12:42:40] [myQ] Initializing myQ platform...
[27/12/2022, 12:42:45] [myQ] myQ API: Successfully connected to the myQ API.
[27/12/2022, 12:42:46] [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: C***, gateway: GW0F
***).
[27/12/2022, 12:42:46] [myQ] myQ API: Discovered device family gateway: Garage Door [Liftmaster WiFi GDO AC 3/4 HP] (serial number
: GW0***).
[27/12/2022, 12:42:46] [myQ] myQ API: Discovered device family gateway: Hub [Chamberlain Smart Garage Hub] (serial number: GW***).
[27/12/2022, 14:00:46] [myQ] Garage Door: Opening.
[27/12/2022, 14:00:53] [myQ] Garage Door: Open.
[27/12/2022, 14:11:09] [myQ] Garage Door: Closing.
[27/12/2022, 14:11:12] [myQ] Garage Door: Closed.

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
`        {
            "email": "nyjklein@panix.com",
            "password": "***********************",
            "refreshInterval": 12,
            "activeRefreshInterval": 3,
            "activeRefreshDuration": 300,
            "debug": true,
            "platform": "myQ"
        },
``

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Homebridge Version:** <!-- homebridge -V --> v1.6.0
* **Node Version:** <!-- node -v --> v18.12.1
* **Homebridge-myQ Plugin Version**: v2.8.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**<!-- Type of Apple device you're using and associated OS version -->
* **Operating System and OS Version:** <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker --> Raspbian GNU/Linux Buster (10)

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by dapostman** [comment]
Same (and continuing) issue as above. Creds work on myq.com.

Only difference over the above log (and it may be a cut/paste thing by the OP) is that I get the Setup Payload: stuff that Homebridge advertises out to HomeKit  before the MyQ API error message.

I *do* greatly appreciate the work here. Hope this is an easy fix.

**Comment by hjdhjd** [comment]
@nyjklein Downgrade to the prior version, out of curiosity and see if things work. Let’s verify the update is the issue first and foremost. Thanks!

**Comment by dapostman** [comment]
Had the same issue with the previous version (2.8.1)

**Comment by csGHcs** [comment]
I experienced the same problem with .2 after updating today.  I just rolled back to homebridge-myq v2.8.1 and I am able to authenticate with no problem.

**Comment by hjdhjd** [comment]
Alright, too many people are weighing in here and this is going to get confusing for me very quickly. 

Let's keep things simple.

To those who are having issues with the latest release, if you have special characters (i.e. something other than a letter and a number), if you could provide a few examples it would be helpful. The only issue that's been consistently reported has been passwords that contain an exclamation point. 

If you are having an issue, my ask: what are the special characters that you're using?

I want to recreate this issue myself and see what I can track down. Thanks.

**Comment by nyjklein** [comment]
My original password that started failing after I upgraded today had two special characters, a ^ and a %. The failures actually locked my account and I was forced to change my password. The new password has only one special character, again a %. and it's still failing.
Jeff

**Comment by dapostman** [comment]
Fair enough, and appreciate the confusion.

I am yet to get the plugin to successfully authenticate via myq.com with my creds ever. 

I have tried short passwords, passwords free of any special characters (alphanumeric only), etc. All passwords provided to the plugin have failed to authenticate, and all have worked fine to log into the myq.com website.

Config and logs provided previously; can provide again as needed/requested.

thanks so much!

**Comment by hjdhjd** [comment]
@dapostman Please open a separate issue if you're having a problem rather than conflating it with this one. the myq.com website cannot be logged into with your myQ credentials, you can only do so with the app. Again - please open a separate issue unless you've been successfully logging in and using this plugin previously and are having an issue with your credentials now. Thanks for keeping this separate.

**Comment by hjdhjd** [comment]
> My original password that started failing after I upgraded today had two special characters, a ^ and a %. The failures actually locked my account and I was forced to change my password. The new password has only one special character, again a %. and it's still failing.
> Jeff

Thanks, I'm testing it myself now...let's see...

**Comment by dapostman** [comment]
Will do, but first…maybe this is it:

I’m a little bit thrown by this note: "the myq.com website cannot be logged into with your myQ credentials, you can only do so with the app.”

I have been thinking that the creds I present through the plugin are the same ones associated with my account at myq.com <http://myq.com/> - am I missing something fundamental?

jp

**Comment by dapostman** [comment]
Will do, but first…maybe this is it:

I’m a little bit thrown by this note: "the [myq.com](http://myq.com/) website cannot be logged into with your myQ credentials, you can only do so with the app.”

I have been thinking that the creds I present through the plugin are the same ones associated with my account at [myq.com](http://myq.com/) - am I missing something fundamental?

jp

**Comment by hjdhjd** [comment]
> My original password that started failing after I upgraded today had two special characters, a ^ and a %. The failures actually locked my account and I was forced to change my password. The new password has only one special character, again a %. and it's still failing.
> Jeff

Alright, I'm able to reproduce this one. I assume you had issues as well with the previous release?

**Comment by monkitrainer** [comment]
@hjdhjd mine also includes % but it works fine in 2.8.1. these chars are included: {%-^_

**Comment by nyjklein** [comment]
The previous release was working with the original password until I upgraded. Then when I tried reverting, it also failed (although the account may have been locked by then).

Jeff

**Comment by hjdhjd** [comment]
@monkitrainer and @nyjklein Thanks. Will be reverting the changes in the next couple of hours. I want to finish testing something (and unlocking my account too 😉)...if you're having an issue, please revert to 2.8.1 and stay tuned.

@nyjklein I suspect your account locked pretty quickly, as mine did as well. So I'd chalk it up to that one.

Thanks!

**Comment by hjdhjd** [comment]
@monkitrainer and @nyjklein Please give v2.8.3 a go. Should do the trick. Sorry about that.

**Comment by dapostman** [comment]
never mind - i used a Hide My Email address in the app on my phone. I’m going to try changing that first.

jp

**Comment by monkitrainer** [comment]
@hjdhjd works fine in 2.8.3. thanks for quick turnaround 👍

**Comment by nyjklein** [comment]
That fixed it for me too!

Thanks!!!

Jeff

**Comment by WheatGuy** [comment]
It's fixed for me. Thanks for fixing so quickly.

**Comment by hjdhjd** [comment]
Thanks all. Let's get back to a nice quiet week...

@dapostman Again - please do not conflate issues you may be having with this one. It creates confusion for folks, including me. 😄 If you have a problem and would like support, please open an issue.

Thanks all.
