### ISSUE TITLE
login failure backoff

### ISSUE THREAD

**Issue by zigg** [hjdhjd/homebridge-myq#965]
**Is your feature request related to a problem? Please describe:**

When I updated to the 2.8.2 release shipped with myq 6.0.8, it appears I had a problem:

```
[12/28/2022, 11:47:26 AM] [myQ] myQ API: Invalid myQ credentials given. Check your login and password.
```

I'm guessing the URI encoding broke on my password, which used to be `PEMQGjMvgVaH!s@d4Rwd`. (It has been changed.)

While the plugin was still trying to send my old password, however, I noticed from the logs it seems to have been consistently trying every two minutes.

myQ locked that account out, though it was easy to recover with a password change.

**Describe the solution you'd like:**

I wonder if the plugin could use an exponential backoff on authentication failure? I've only been using this couple weeks, and I don't know how often myQ throws authentication issues that are just due to service errors.

**Describe alternatives you've considered:**

Another possibility: could the plugin simply stop trying to log in and indicate some kind of error through HomeKit?

**Additional context:**

I'm willing to do some code work on this if you think it's worthwhile. Thanks for considering it, and thanks for maintaining this!

**Comment by hjdhjd** [comment]
Thanks, a future update will address this.
