### ISSUE TITLE
Repeated DNS queries

### ISSUE THREAD

**Issue by nickp85** [hjdhjd/homebridge-myq#980]
**Describe The Problem:**

I am seeing constant DNS queries for the myq server. Not an issue as much as it is highly inefficient so wanted to report it

**To Reproduce:**

Look at your DNS server while the myq plugin is running in HomeBridge

**Logs:**

```

Running Homebridge in Docker on Unraid and it doesn't seem to perform logging.
Cannot show logs. "log" option is not configured correctly in your Homebridge config.json file.

See https://homebridge.io/w/JtHrm for instructions or use hb-service.
```

**Homebridge Configuration:**

```json
        {
            "email": "XXXXXXXXX",
            "password": "XXXXXXXXXXXXXXXX",
            "platform": "myQ",
            "_bridge": {
                "username": "0E:EA:34:11:A4:3D",
                "port": 42847
            }
        },
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/59027847/213898405-d5a2aefb-093a-42b9-96ce-29f7d2039353.png)

**Environment:**

* **Homebridge Version:**  1.6.0
* **Node Version:**  v16.7.0
* **Homebridge-myQ Plugin Version**: 2.9.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 Pro, iOS 16.3
* **Operating System and OS Version:**  Docker on Unraid

**Comment by hjdhjd** [comment]
This is not a bug. This is by design. You can lookup older issues that inquired about this if it’s of curiosity. TL;DR: this plugin polls the myQ cloud regularly.
