### ISSUE TITLE
DNS Cache Recommendation

### ISSUE THREAD

**Issue by apearson** [hjdhjd/homebridge-myq#984]
**Is your feature request related to a problem? Please describe:**
I see that you've gotten a couple of issues related to DNS requests.  #755 #980 

**Describe the solution you'd like:**
One solution would be to recommend the following to be added to the homebridge startup script.  This installs and starts the nscd (Name Service Cache Daemon) and will enable a local dns cache in the homebridge container. 

```
service nscd start
```

**Describe alternatives you've considered:**
I considered adding this to the two issues so that future searchers stumbling onto the github issues would have the solution right in front of them.  

An alternative would be to add it to the README but it's not a homebridge-mq specific issue. 

```
- <A NAME="dns-queries"></A> If you want to reduce the number of DNS queries generated, use the following in your startup script.  This installs and starts the nscd (Name Service Cache Daemon) and will enable a local dns cache in the homebridge container. 
    ```
    service nscd start
    ```
```

Thank you for taking the time to read this.
 \- @apearson

**Comment by hjdhjd** [comment]
Thanks for the suggestion but this is really a reference point for those interested in this topic. Happy to leave the issue in case people want to go searching for it, but I won’t be adding this to the plugin.

Again - as stated previously: this has nothing to do with the plugin. If the number of DNS queries this plugin generates during it’s normal operation is something that keeps you up at night…I can’t help you with that. 😄
