### ISSUE TITLE
Door sensor

### ISSUE THREAD

**Issue by JobWhisperer** [hjdhjd/homebridge-myq#997]
So I’m trying to create an automation in HomeKit, where if my garage door has been open for more than an hour and a half HomeKit will shut the door. With the available options and automations and my limited knowledge of Shortcuts, I don’t see the options after either an accessory has been controlled or a sensor detects something. I’m wondering if the sensor on the actual door can be revealed in home bridge so that the automation or shortcut can take advantage of its state. After triggering an open or close of the door, I’ve seen on a status that the garage door is either opening or closing so I know there is some reporting somewhere but not sure how to expose it. Any help would be greatly appreciated.  in the myQ app, I have previously set up as scheduled but the schedule is not conditional and only triggers at a certain time of day. 

**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by sfguyfor20** [comment]
I do the same thing... I use a dummy switch with a timer on it...

**Comment by JobWhisperer** [comment]
Sounds like a Monday morning challenge.  The problem is, is this dummy switch hardware or software and how/where do I create it?

**Comment by sfguyfor20** [comment]
well, several options... currently I use the hoobs dummy switch... 
![image](https://user-images.githubusercontent.com/73134472/220128249-bbfc613b-7ac8-4228-a30e-9a3c81b2afc4.png)

before that, I used a hues smart plug...

**Comment by JobWhisperer** [comment]
Had no clue about this dummy switch!  Thanks…I’m reading up on them now.
Have a good start to the week!

**Comment by jr-79** [comment]
Would I be able to use this dummy switch to detect if my MyQ garage door opener is open for a certain amount of time, and trigger another HomeKit device? I’m trying to turn off my garage heater if the door is open for 300 seconds. And resume once closed? I was going to use an Eve door sensor for this, but the MyQ seems like a better source of truth.

**Comment by sfguyfor20** [comment]
Based on your use case.. is that the heater is a smart heater, or are you using a smart plug...?
